### PR TITLE
Fix uninitialized constant Parser::AST::Processor::Mixin

### LINKED ISSUE #7029: uninitialized constant Parser::AST::Processor::Mixin with parser 3.3.1.0
# Describe the problem

parser 3.3.1.0 introduced https://github.com/whitequark/parser/pull/1000, which causes this failure:

```shell
% bundle exec ruby -Itest test/unit/profiles/profile_test.rb
/Users/stanhu/github/inspec/lib/inspec/utils/profile_ast_helpers.rb:7:in `<class:CollectorBase>': uninitialized constant Parser::AST::Processor::Mixin (NameError)

        include Parser::AST::Processor::Mixin
                                      ^^^^^^^
Did you mean?  Mixlib
	from /Users/stanhu/github/inspec/lib/inspec/utils/profile_ast_helpers.rb:6:in `<class:AstHelper>'
	from /Users/stanhu/github/inspec/lib/inspec/utils/profile_ast_helpers.rb:5:in `<class:Profile>'
	from /Users/stanhu/github/inspec/lib/inspec/utils/profile_ast_helpers.rb:4:in `<module:Inspec>'
	from /Users/stanhu/github/inspec/lib/inspec/utils/profile_ast_helpers.rb:3:in `<top (required)>'
	from <internal:/Users/stanhu/.asdf/installs/ruby/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/stanhu/.asdf/installs/ruby/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/stanhu/github/inspec/lib/inspec/profile.rb:18:in `<top (required)>'
	from <internal:/Users/stanhu/.asdf/installs/ruby/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/stanhu/.asdf/installs/ruby/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from test/unit/profiles/profile_test.rb:6:in `<main>'
```

## Possible Solution

```diff
diff --git a/inspec.gemspec b/inspec.gemspec
index 4ff761e48..83c4526a9 100644
--- a/inspec.gemspec
+++ b/inspec.gemspec
@@ -54,5 +54,5 @@ Source code obtained from the Chef GitHub repository is made available under Apa
   spec.add_dependency "train-kubernetes", "~> 0.1"
 
   spec.add_dependency "mongo", "= 2.13.2" # 2.14 introduces a broken symlink in mongo-2.14.0/spec/support/ocsp
-
+  spec.add_dependency "parser", ">= 3.3.1.0" # 3.3.1.0 removed a mix-in: https://github.com/whitequark/parser/pull/1000
 end
diff --git a/lib/inspec/utils/profile_ast_helpers.rb b/lib/inspec/utils/profile_ast_helpers.rb
index 8e00206f8..299e85bd5 100644
--- a/lib/inspec/utils/profile_ast_helpers.rb
+++ b/lib/inspec/utils/profile_ast_helpers.rb
@@ -3,8 +3,7 @@ require "rubocop-ast"
 module Inspec
   class Profile
     class AstHelper
-      class CollectorBase
-        include Parser::AST::Processor::Mixin
+      class CollectorBase < Parser::AST::Processor
         include RuboCop::AST::Traversal
 
         attr_reader :memo
```

The dependency graph:

`inspec-core` -> `rubocop-ast` -> `parser >= 3.3.0.4`

When `parser` 3.3.1.0 was released today, the previous mix-in no longer exists.

### PR DESCRIPTION
**Pull request by stanhu**
## Description

parser 3.3.1.0 introduced https://github.com/whitequark/parser/pull/1000, which causes this failure:

```
% bundle exec ruby -Itest test/unit/profiles/profile_test.rb
inspec/lib/inspec/utils/profile_ast_helpers.rb:7:in `<class:CollectorBase>': uninitialized constant Parser::AST::Processor::Mixin (NameError)

        include Parser::AST::Processor::Mixin
                                      ^^^^^^^
```

Fix this by inherting from `Parser::AST::Processor` and requiring the right version of the `parser` gem.

## Related Issue

Closes #7029

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by ahasunos — APPROVED** [review]

File: lib/inspec/utils/profile_ast_helpers.rb [hunk 1]
```diff
@@ -3,8 +3,7 @@
 module Inspec
   class Profile
     class AstHelper
-      class CollectorBase
-        include Parser::AST::Processor::Mixin
+      class CollectorBase < Parser::AST::Processor
```
Comment (ahasunos) [inline lib/inspec/utils/profile_ast_helpers.rb:6]: I've verified that this applies to older versions (i.e. < 3.3.1.0) of `parser` gem  as well. I believe we don't need to explicitly specify the gem in the gemspec with that constraint. What do you think?

File: inspec.gemspec [hunk 2]
```diff
@@ -54,5 +54,5 @@ Source code obtained from the Chef GitHub repository is made available under Apa
   spec.add_dependency "train-kubernetes", "~> 0.1"
 
   spec.add_dependency "mongo", "= 2.13.2" # 2.14 introduces a broken symlink in mongo-2.14.0/spec/support/ocsp
-
+  spec.add_dependency "parser", ">= 3.3.1.0" # 3.3.1.0 removed a mix-in
```
Comment (ahasunos) [inline inspec.gemspec]: In support of the previous comment, this line could be removed.

File: lib/inspec/utils/profile_ast_helpers.rb (hunk 1 above)
Comment (stanhu) [reply lib/inspec/utils/profile_ast_helpers.rb:6]: Ah, right. Thanks.

**Comment by aaronlippold** [comment]
What's the current work around for existing releases, like 6.6.0?

**Comment by stanhu** [comment]
> What's the current work around for existing releases, like 6.6.0?

Use `parser` v3.3.0.5.

**Comment by aaronlippold** [comment]
Aka throw that in the Gemfile of my profile? Working to fix my current pipeline while we wait on the patch.

**Comment by stanhu** [comment]
> Aka throw that in the Gemfile of my profile? Working to fix my current pipeline while we wait on the patch.

Yes, lock it down. 😄

**Comment by aaronlippold** [comment]
Cool, I will give that a try, or more specifically @wdower will :)

**Comment by ruairiquinn-bv** [comment]
> > What's the current work around for existing releases, like 6.6.0?
> 
> Use `parser` v3.3.0.5.

We tried this but without much success, any idea when this fix will be merged?

```
[2024-05-01T16:45:21.517Z] Fetching gem metadata from https://rubygems.org/........
[2024-05-01T16:45:22.032Z] Resolving dependencies....
[2024-05-01T16:45:22.032Z] Bundler could not find compatible versions for gem "parser":
[2024-05-01T16:45:22.032Z]   In Gemfile:
[2024-05-01T16:45:22.032Z]     parser (= 3.3.0.5)
[2024-05-01T16:45:22.032Z] 
[2024-05-01T16:45:22.032Z]     kitchen-inspec was resolved to 2.6.2, which depends on
[2024-05-01T16:45:22.032Z]       inspec (>= 2.2.64, < 6.0) was resolved to 5.22.40, which depends on
[2024-05-01T16:45:22.032Z]         cookstyle was resolved to 7.32.8, which depends on
[2024-05-01T16:45:22.032Z]           rubocop (= 1.25.1) was resolved to 1.25.1, which depends on\
[2024-05-01T16:45:22.032Z] rubocop-ast (>= 1.15.1, < 2.0) was resolved to 1.31.3, which depends
[2024-05-01T16:45:22.032Z] on
[2024-05-01T16:45:22.032Z]               parser (>= 3.3.1.0)
```

**Comment by ahasunos** [comment]
> > > What's the current work around for existing releases, like 6.6.0?
> > 
> > 
> > Use `parser` v3.3.0.5.
> 
> We tried this but without much success, any idea when this fix will be merged?
> 
> ```
> [2024-05-01T16:45:21.517Z] Fetching gem metadata from https://rubygems.org/........
> [2024-05-01T16:45:22.032Z] Resolving dependencies....
> [2024-05-01T16:45:22.032Z] Bundler could not find compatible versions for gem "parser":
> [2024-05-01T16:45:22.032Z]   In Gemfile:
> [2024-05-01T16:45:22.032Z]     parser (= 3.3.0.5)
> [2024-05-01T16:45:22.032Z] 
> [2024-05-01T16:45:22.032Z]     kitchen-inspec was resolved to 2.6.2, which depends on
> [2024-05-01T16:45:22.032Z]       inspec (>= 2.2.64, < 6.0) was resolved to 5.22.40, which depends on
> [2024-05-01T16:45:22.032Z]         cookstyle was resolved to 7.32.8, which depends on
> [2024-05-01T16:45:22.032Z]           rubocop (= 1.25.1) was resolved to 1.25.1, which depends on\
> [2024-05-01T16:45:22.032Z] rubocop-ast (>= 1.15.1, < 2.0) was resolved to 1.31.3, which depends
> [2024-05-01T16:45:22.032Z] on
> [2024-05-01T16:45:22.032Z]               parser (>= 3.3.1.0)
> ```

It would be merged today!

**Comment by stanhu** [comment]
>  We tried this but without much success

It looks like `rubocop-ast` 1.31.3 was updated to require `parser >= 3.3.1.0` (https://rubygems.org/gems/rubocop-ast) via https://github.com/rubocop/rubocop-ast/pull/289.

Locking `rubocop-ast` to 1.31.2 and `parser` to 3.3.0.5 would be the current workaround.

**Comment by aaronlippold** [comment]
That works for me

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by stanhu** [comment]
@ahasunos I see there is a v6.6.19 tag with this change (https://github.com/inspec/inspec/commit/9939b0d220a0627e8c034eda467efd878a3da7cc), but https://rubygems.org/gems/inspec still only shows 6.6.0 published. Do you know what it takes to publish this to RubyGems?

**Comment by ruairiquinn-bv** [comment]
> > We tried this but without much success
> 
> It looks like `rubocop-ast` 1.31.3 was updated to require `parser >= 3.3.1.0` (https://rubygems.org/gems/rubocop-ast) via [rubocop/rubocop-ast#289](https://github.com/rubocop/rubocop-ast/pull/289).
> 
> Locking `rubocop-ast` to 1.31.2 and `parser` to 3.3.0.5 would be the current workaround.

Thanks, that did the trick!
