### PR TITLE
Fix postgres_session resource to raise exception if there is a error in connection or in query

### LINKED ISSUE #5309: SQL session resources should throw an error or warning if you try to execute a query but there is no valid session established
At the moment - if for some reason the sql session of the database resources do not make it clear that you are trying to query a nil sql session and it is cauing invalid results.

We should add some logic in the session and the query resources to protect aginst this case.

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

Fix postgres_session resource to raise exception if database connection is not established due to any reason or there is error with query. Currently it does not raise any exception due to which the InSpec test gives false result.

## Related Issue

Fixes #5309 for postgres_session resource
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/postgres_session.rb [hunk 1]
```diff
@@ -45,21 +45,30 @@ def initialize(user, pass, host = nil, port = nil)
...
-        Lines.new(out, "PostgreSQL query with errors: #{query}")
+        raise Inspec::Exceptions::ResourceFailed, "PostgreSQL query with errors: #{out}"
       else
         Lines.new(cmd.stdout.strip, "PostgreSQL query: #{query}")
       end
     end
 
     private
 
+    def set_connection
```
Comment (clintoncwolfe) [inline lib/inspec/resources/postgres_session.rb]: Let's rename this to be test_connection and use a more generic query like SELECT 1

**Review by clintoncwolfe — APPROVED** [review]
Looks good, will merge after release tomorrow.
