### PR TITLE
Fix exceptions when resources are used with incompatible transports

### LINKED ISSUE #4208: File resource source_path 'undefined method `source_path`'
```
sudo inspec exec . -t aws://
Traceback (most recent call last):
	26: from /usr/local/bin/inspec:153:in `<main>'
	25: from /usr/local/bin/inspec:153:in `load'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.3/bin/inspec:11:in `<top (required)>'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/cli.rb:297:in `exec'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:121:in `run'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:114:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:114:in `each'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:115:in `block in load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `register_rule'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `flat_map'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `each'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:273:in `block in register_rule'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:261:in `get_check_example'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:287:in `rspec_failed_block'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner_rspec.rb:25:in `example_group'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:386:in `subclass'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:422:in `set_it_up'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:258:in `create'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:133:in `populate'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/resources/file.rb:167:in `to_s'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/resources/file.rb:53:in `block (2 levels) in <class:FileResource>': undefined method `source_path' for nil:NilClass (NoMethodError)
```

### PR DESCRIPTION
**Pull request by zenspider**
Fixes #4208

### CODE REVIEW

File: test/functional/inspec_exec_test.rb [hunk 1]
```diff
@@ -4,13 +4,37 @@
   include FunctionalHelper
   let(:looks_like_a_stacktrace) { %r{lib/inspec/.+\.rb:\d+:in} }
 
+  attr_accessor :out
+
+  def inspec(commandline, prefix = nil)
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_test.rb:9]: This file contains the majority of the deltas for the PR.

I was initially unclear on why this is being redefined here (there is a method with the same name and sam e intended functionality in `functional/helper.rb`). We have several generations of methods that will run an inspec process - `run_inspec_process` being my personal favorite. 

It appears that you wanted to expose stdout and stderr as a refactor (and avoid `out` and the `force_encoding`) - which is good idea, but many of the other functional test files that use `inspec()` have the same issues.  

Anyway, what does this have to do with `file` on incompatible transports? Could this be pushed out to a separate PR that catches the other test files, and doesn't get pulled in like this?

File: test/unit/mock/profiles/bad.rb [hunk 2]
```diff
@@ -0,0 +1,3 @@
+describe file('/tmp/foo') do
```
Comment (clintoncwolfe) [inline test/unit/mock/profiles/bad.rb]: Please, we are trying to keep our fixtures organized; please store your fixtures under directories with meaningful names. In what way is this "bad"? It is because it is a bare control file with no metadata (which is legal)? Or a legal though failing file control referencing a non-existant file? `resource_on_bad_platform/missing_file.rb` ?

File: lib/inspec/resources/file.rb [hunk 3]
```diff
@@ -165,7 +165,11 @@ def more_permissive_than?(max_mode = nil)
     end
 
     def to_s
-      "File #{source_path}"
+      if file
+        "File #{source_path}"
+      else
+        "Bad File on %s" % [inspec.backend.class]
```
Comment (clintoncwolfe) [inline lib/inspec/resources/file.rb:171]: This set of lines is the important code in this PR; there is also some related test code. Most of the rest of the code delta is a test file refactor.

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
The fix here is simple and good, but there is an incompletely applied test file refactor that is unrelated.  Either it should be applied everywhere or not involved on this PR, I think. Also, there is an entropy-increasing test fixture file - try to use meaningful names. Thanks!

File: lib/inspec/resources/file.rb (hunk 3 above)
Comment (zenspider) [reply lib/inspec/resources/file.rb:171]: Yes, as described verbosely in the commits.

File: test/functional/inspec_exec_test.rb (hunk 1 above)
Comment (zenspider) [reply test/functional/inspec_exec_test.rb:9]: As described in the commits, this refactoring of the test file cleans up both the IO redundancy throughout the entire file and also reorders the exit code checks to be last so that failing tests are actually debuggable.

Putting this in a separate PR doesn't make sense in this instance. Having 4 PRs with single commits that must be stacked in order to get the real work done instead of a single PR with 4 commits that all do small(ish) unrelated but overlapping things only serves to slow us down and add bureaucratic process where none is needed.

Comment (zenspider) [reply test/functional/inspec_exec_test.rb:9]: Putting this in a separate PR doesn't make sense in this instance. Having 4 PRs with single commits that must be stacked in order to get the real work done instead of a single PR with 4 commits that all do small(ish) unrelated but overlapping things only serves to slow us down and add bureaucratic process where none is needed.

File: test/unit/mock/profiles/bad.rb (hunk 2 above)
Comment (miah) [reply test/unit/mock/profiles/bad.rb]: +1 a comment describing what we're testing would be useful.

**Review by miah — APPROVED** [review]
Thanks @zenspider

File: test/unit/mock/profiles/bad.rb (hunk 2 above)
Comment (zenspider) [reply test/unit/mock/profiles/bad.rb]: Happy to rename it something else. Done.

**Review by clintoncwolfe — APPROVED** [review]
