### PR TITLE
tests: Fix profile_context_test NameError

### LINKED ISSUE #3721: Investigate failing test when using `m` and `test/unit/profiles/profile_context_test.rb`
Running the below

```
bundle exec m test/unit/profiles/profile_context_test.rb --line 114 
```

Errors with:

```
Inspec::ProfileContext::its default DSL#test_0007_does not provide the expect keyword in the global DLS [/home/jerry/Projects/github.com/inspec/inspec/test/unit/profiles/profile_context_test.rb:114]:
[NoMethodError] exception expected, not
Class: <NameError>
Message: <"uninitialized constant Inspec::Plugin\nDid you mean?  Inspec::Plugins">
---Backtrace---
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `instance_eval'
(eval):1:in `load_with_context'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `instance_eval'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `load_with_context'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:144:in `load_control_file'
/home/jerry/Projects/github.com/inspec/inspec/test/unit/profiles/profile_context_test.rb:69:in `block in load'
---------------
```

This works when doing `bundle exec rake` so I suspect there is a path through the code that fails to load something but I couldn't find it after searching for 20 minutes.

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This closes #3721

### CODE REVIEW

File: lib/inspec/dsl.rb [hunk 1]
```diff
@@ -31,6 +31,7 @@ def require_resource(options = {})
   # This is called when an unknown method is encountered
   # "bare" in a control file - outside of a control or describe block.
   def method_missing(method_name, *arguments, &block)
+    require 'inspec/plugin/v2'
```
Comment (clintoncwolfe) [inline lib/inspec/dsl.rb]: @jerryaldrichiii, can you explain why this location was chosen for the `require`? It would seem more typical to require in the top of `lib/inspec/dsl.rb`, or in `lib/inspec/profile_context.rb` (which is where the error appeared).

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
Surprising location for a require; I'd want to know why (and explain with a comment).

File: lib/inspec/dsl.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply lib/inspec/dsl.rb]: Great call out. I could use some words on describing the behavior succinctly. I believe the issue is because we are doing an `instance_eval`. The only places I could get it to work were to place the require here: https://github.com/inspec/inspec/blob/master/lib/inspec/profile_context.rb#L152 or the place you see it. I did the latter since it is closer to https://github.com/inspec/inspec/blob/852085969fe85d7a69157eb4304e075625ca8e68/lib/inspec/dsl.rb#L36

Placing at the top of the files like you would expect leads me down a rabbit hole that I couldn't get to the bottom of (issues like not being able to find `Inspec::BaseCLI`).

Comment (clintoncwolfe) [reply lib/inspec/dsl.rb]: If you'd like to pair or group work on this, I'd be happy to do so; I'm familiar with the missing require for BaseCLI from the plugin/v2/plugin_types/cli type.  Simple fix there.

Comment (jerryaldrichiii) [reply lib/inspec/dsl.rb]: Oh? Great! I'll bring it up in standup and we can get some time scheduled if the usual parking lot time doesn't cover it.

**Review by clintoncwolfe — APPROVED** [review]
Thanks @jerryaldrichiii

**Review by miah — APPROVED** [review]
