### PR TITLE
Fix for security_policy resource does not return array for local groups

### LINKED ISSUE #5627: Inspec security_policy resource does not return array for local groups
# Describe the problem
Customer having some issues with the Inspec security policy resource. When the security right contains local groups (rather than SIDs), the inspec resource returns a comma-separated string, rather than an array.

For example, this code error
```
describe security_policy do
 its('SeServiceLogonRight') { should match_array ['SSRSServices' ,'SQLServices'] }
end
```
with the following message
```
 Security Policy
 [FAIL] SeServiceLogonRight is expected to contain exactly "SSRSServices" and "SQLServices"
 expected a collection that can be converted to an array with `#to_ary` or `#to_a`, but got "SQLServices,SSRSServices"
```
Other user rights assignments (which contain SIDs) work as expected
```
administrators = 'S-1-5-32-544'
power_users = 'S-1-5-32-547'
describe security_policy do
 its('SeInteractiveLogonRight') { should match_array ['SSRSUnattendExec', administrators, power_users] }
end
```
The User confirmed this issue occurs in multiple environments and occurs with both local and group policy.

Expected behavior
Not sure if it is expected for local groups, if not It should be working for local groups as well.

Customer bug : https://github.com/chef/customer-bugs/issues/460

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

security_policy resource was not returning values in array format when Privilege rights contain any local groups only. This is fixed in this PR.

So when any security policy for privilege rights containing only local group it does not contain the SID for example values are like below
`SeServiceLogonRight = DB2ADMNS,db2admin`

Where as if there are values other than local group then values are 
`SeServiceLogonRight = DB2ADMNS,db2admin,*S-1-5-80-0`

## Related Issue

Fix #5627 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/security_policy.rb [hunk 1]
```diff
@@ -166,14 +166,15 @@ def extract_value(val)
       elsif !(m = /^\"(.*)\"$/.match(val)).nil?
         m[1]
       else
-        val
+        # When there is Registry Values we are not spliting the value for backward compatibility
+        key.include?("\\") ? val : val.split(",")
```
Comment (Nik08) [inline lib/inspec/resources/security_policy.rb:170]: Would you mind explaining this check `key.include?("\\")` ?

Comment (Vasu1105) [reply lib/inspec/resources/security_policy.rb:170]: I have added my comments but yes we get some values of Registry Path as `MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Setup\\RecoveryConsole\\SecurityLevel=4,0` which we are not going to split as there are chances that it will break if anyone is using string comparison. Check the existing test case where you will get a better idea.

**Comment by Nik08** [comment]
Lgtm
