### PR TITLE
Permit plugin to be in path with git ref

### LINKED ISSUE #3904: Cannot load git-referenced bundled plugin
Using 3.7.11 from a gem install

```
➜  my-cool-project git:(my_branch) ✗ bundle exec inspec plugin install $(bundle show inspec-something)
Unrecognizable plugin structure - inspec-something-812f55372c8e - When installing from a path, please provide the path of the entry point file - installation failed.
```

The plugin source is at `/Users/jamesstocks/code/my-cool-project/vendor/bundle/ruby/2.3.0/bundler/gems/inspec-something-812f55372c8e/lib/inspec-something.rb`

Looking at the supported plugin loading cases [here](https://github.com/inspec/inspec/blob/master/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L225) it looks like this setup does not match a supported case.

Workaround:
`ln -s $(bundle show inspec-something) ~/.inspec/plugins/inspec-something` works, but symlinking in a plugin like this is not recommended/supported.

### PR DESCRIPTION
**Pull request by james-stocks**
Fixes #3904

Signed-off-by: James Stocks <jstocks@chef.io>

## Description

Fixes https://github.com/inspec/inspec/issues/3904 by allowing a plugin to be found in a folder that refers to a git SHA e.g. `/Users/jamesstocks/code/bundles/cool-project/ruby/2.4.0/bundler/gems/inspec-special-62e42ce9eca1`

## Related Issue

#3904

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb [hunk 1]
```diff
@@ -229,6 +229,7 @@ def install_from_path__apply_entry_point_heuristics(path) # rubocop: disable Met
         given = given.expand_path # Resolve any relative paths
         name_regex = /^(inspec|train)-/
         versioned_regex = /^(inspec|train)-[a-z0-9\-\_]+-\d+\.\d+\.\d+$/
+        sha_ref_regex = /^(inspec|train)-[a-z0-9\-\_]+-[0-9a-f]{5,40}$/
```
Comment (james-stocks) [inline lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:232]: I could make a single regex that matches either of these 2 regexes.
That would keep the lines changed below simpler; but might make the regex(es) unreasonable to follow.

**Comment by james-stocks** [comment]
I couldn't find existing unit tests that cover the `CliCommand` class that's changed by this PR.
I can add some unit tests if I get a pointer on the right place in the current test setup to add them.

**Review by clintoncwolfe — APPROVED** [review]
Thanks for this - after a zoom discussion, we determined that this is needed for CI on the Compliance Profiles team, not just for developer convenience. This PR doesn't currently have any docs or testing on it, but as it is likely to only be used by the Content team and they are willing to accept those risks, I feel OK accepting this without tests. If you want to add tests, @james-stocks, they would go here: https://github.com/inspec/inspec/blob/cec41211526845f5850929e863a02a01f0625e1e/lib/plugins/inspec-plugin-manager-cli/test/functional/inspec-plugin_test.rb#L265

**Review by miah — APPROVED** [review]
