### PR TITLE
Catch cloud exceptions and document connection info

### LINKED ISSUE #2612: Azure/Aws connection documentation
Documentation: It is not easy to get started. We need documentation about how to setup (e.g. get the access token) and we need to support the default aws/azure client configuration to make the experience seamless. (e.g.  ~/.aws/credentials and ~/.aws/config)

### LINKED ISSUE #2613: Azure/Aws resources should not hard fail on API exceptions
A profile needs to be executable, but a control may fail. We currently throw exceptions for resources that stop full profile execution, resulting in no report. This will lead to issues if we expect json output e.g in Chef Automate. The controls needs to fail (ie, have a failure outcome but absorb any exceptions) if the resource cannot be executed, but we need to generate a report.

We should hook into the fail_resource if the resource connection is bad saying such.

### PR DESCRIPTION
**Pull request by clintoncwolfe**
Adds a document describing the credentials setup for AWS and Azure, fixes #2612 

Adds a method, `catch_aws_errors`, to the AwsResourceMixin.  Intercepts connection exceptions and provides a friendlier error message.  Intercepts all other AWS errors and calls `fail_resource`, allowing the inspec run to continue while marking the test/control failed.  Added wrapper around lazy-fetched properties, and copy-pasted the code to get three more resources covered (#2633 logged as tech debt).  

Adds a method, `catch_azure_errors`, to AzureResourceBase.  Catches Azure exceptions (there appears to only be one class; they are otherwise distinguished by a JSON structure).  Due to how properties are dynamically generated, it was necessary to add an instance variable as a sentinel for whether the resource had failed, and then treat any unknown property as nil, which is ugly. 

The AWS and Azure changes together fix #2613.

### CODE REVIEW

File: lib/resources/aws/aws_iam_user.rb [hunk 1]
```diff
@@ -82,6 +82,8 @@ def fetch_from_api
 
     # TODO: consider returning Inspec AwsIamAccessKey objects
     @access_keys = backend.list_access_keys(user_name: username).access_key_metadata
```
Comment (jquick) [inline lib/resources/aws/aws_iam_user.rb:84]: does this need wrapped in catch_aws_errors?

**Review by jquick — APPROVED** [review]
Looking good! Thanks for this @clintoncwolfe

File: docs/platforms.md [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+
+Look for a file in your home directory named `~/.aws/credentials`.  If it does not exist, create it.  Add your credentials as a new profile, in INI format:
+
+```
+[my-profile-name]
+aws_access_key_id = AKIA....
+aws_secret_access_key = 1234....abcd
+```
+
+You may now run InSpec using the `--target` / `-t` option, using the format `-t aws://region/profile`.  For example, to connect to the Ohio region using a profile named 'auditing', use `-t aws://us-east-2/auditing`.
```
Comment (chris-rock) [inline docs/platforms.md:41]: Are you referring to the profile from the `.aws/credentials` or is that a different one. If so, we may use the same name for the profile. I'd like the `auditing` profile name.

File: docs/platforms.md [hunk 3]
```diff
@@ -0,0 +1,88 @@
+# Using InSpec 2.0 with Platforms
+
+New in InSpec 2.0, you may now use certain InSpec resources to audit properties of things that aren't individual machines - for example, an Amazon Web Services S3 bucket.
+
+In the initial release of InSpec 2.0, support for selected AWS and Azure resources is included.
+
+## AWS Platform Support in InSpec 2.0
```
Comment (chris-rock) [inline docs/platforms.md]: I think we do not need to name InSpec 2.0 here again

File: docs/platforms.md [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+Look for a file in your home directory named `~/.aws/credentials`.  If it does not exist, create it.  Add your credentials as a new profile, in INI format:
+
+```
+[my-profile-name]
+aws_access_key_id = AKIA....
+aws_secret_access_key = 1234....abcd
+```
+
+You may now run InSpec using the `--target` / `-t` option, using the format `-t aws://region/profile`.  For example, to connect to the Ohio region using a profile named 'auditing', use `-t aws://us-east-2/auditing`.
+
```
Comment (chris-rock) [inline docs/platforms.md:42]: Should we include the `inspec detect` as an example to verify that the credentials and the connection works?

**Review by chris-rock — APPROVED** [review]
@clintoncwolfe Great additions. I added some questions regarding the documentation. We can fix those in follow-up PRs

File: docs/platforms.md [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+The simplest way is to create the file `~/.azure/credentials` with the following format. InSpec is configured to look for this file by default, so no settings are required.
+
+```
+[<SUBSCRIPTION_ID>]
+client_id = "<CLIENT_ID>"
+client_secret = "<CLIENT_SECRET>"
+tenant_id = "<TENANT_ID>"
+```
+
+So to run InSpec now it is as simple as running:
```
Comment (miah) [inline docs/platforms.md]: This could read better like "With the credentials are in place you may now execute InSpec"

File: docs/platforms.md [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+
+- Azure CLI: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authenticate-service-principal-cli
+- PowerShell: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authenticate-service-principal
+- Azure Portal: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal
+
+The information from the SPN can be specified either in a file `~/.azure/credentials`, as environment variables, or using InSpec target URIs.
+
+#### Using the Azure Credentials File
+
+The simplest way is to create the file `~/.azure/credentials` with the following format. InSpec is configured to look for this file by default, so no settings are required.
```
Comment (miah) [inline docs/platforms.md]: "By default InSpec is configured to look at `~/.azure/credentials`, and it should contain:" or "By default InSpec is configured to look at `~/.azure/credentials`, and the format is:"

File: docs/platforms.md (hunk 2 above)
Comment (clintoncwolfe) [reply docs/platforms.md:41]: 👍

File: docs/platforms.md (hunk 4 above)
Comment (clintoncwolfe) [reply docs/platforms.md:42]: This may be misleading.  Train's AWS support doesn't test the connection until an API call is actually tried.
