### PR TITLE
nginx_conf: Fix commented/empty file parsing

### LINKED ISSUE #2790: nginx_conf resource cannot handle include of empty files
### 🐛 Description

The `nginx_conf` resource will return an empty `params` if an included configuration file is empty. This also occurs if the included configuration file consists of only comments. An empty included file should have no effect. The use case where this issue occurred was where we had an `nginx.conf` include a sample configuration file which is itself completely commented out.

### 🌍 InSpec and Platform Version

2.0.32
OSX 10.13.3

### 🤔 Replication Case

The issue can be demonstrated with the following toy example of an `nginx.conf` file.

```
http {
    default_type  application/octet-stream;
}
```

Executing the following in the shell to get the parsed params using the `nginx_conf` resource:
```
inspec> nginx_conf('nginx.conf').params
=> {"http"=>[{"default_type"=>[["application/octet-stream"]]}]}
``` 

Create an empty file called `empty.conf` and add an in include statement to `nginx.conf`:
```
http {
    include empty.conf;
    default_type  application/octet-stream;
}
```

Getting the params again from the shell:
```
inspec> nginx_conf('nginx.conf').params
=> {}
```

Adding an empty `server` directive to `empty.conf`:
```
server {}
```

Getting the params from the shell now works fine:
```
inspec> nginx_conf('nginx.conf').params
=> {"http"=>[{"default_type"=>[["application/octet-stream"]], "server"=>[{}]}]}
```

### 💁 Possible Solutions
Not sure the exact fix.  Probably somewhere in [lib/utils/nginx_parser.rb](https://github.com/chef/inspec/blob/master/lib/utils/nginx_parser.rb) or [lib/resources/nginx_conf.rb](https://github.com/chef/inspec/blob/master/lib/resources/nginx_conf.rb).

### 💻 Stacktrace
See output in Replication Case.

### LINKED ISSUE #4198: Can't gather config using nginx_conf
# Describe the problem
When using nginx_config in the inspec shell can't get to grab any config there.

```Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      centos
    Families:  redhat, linux, unix, os
    Release:   7.6.1810
    Arch:      x86_64

inspec> nginx_conf
=> nginx_conf /etc/nginx/nginx.conf
inspec> nginx_conf.params
=> {}
inspec>
```

## Possible Solution
NA

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
## Description

This fixes `nginx_conf.params` when:
  - Given an empty file
  - Given a file with only comments
  - Given a file that has an include for a file that:
    - Is empty
    - Has all lines commented out

## Related Issues

This fixes #4198 
This fixes #2790

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/nginx_conf.rb [hunk 1]
```diff
@@ -63,6 +63,11 @@ def read_content(path)
     def parse_nginx(path)
       return nil if inspec.os.windows?
       content = read_content(path)
+
+      # Don't attempt to parse file if it contains only comments or is empty
+      # https://regexper.com/#%2F%5E%5Cs*%23%7C%5E%24%2F
+      return {} if content.split("\n").reject { |l| l =~ /^\s*#|^$/ } == []
```
Comment (clintoncwolfe) [inline lib/inspec/resources/nginx_conf.rb]: Might try this, it's a bit more idiomatic:
```
content.lines.reject { |l| l =~ /^\s*#|^$/ }.empty?
```

**Review by clintoncwolfe — APPROVED** [review]
I just had a brief comment about idiomatic ruby, which is OK by me - thanks for this!

File: lib/inspec/resources/nginx_conf.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply lib/inspec/resources/nginx_conf.rb]: Will do! I like yours better anyway.

**Review by miah — APPROVED** [review]
