### PR TITLE
More meaningful error when including controls from a missing dependency

### LINKED ISSUE #3769: Unclear error message when using `include_controls` with a profile not defined in `inspec.yml`
### 🎛 Description

**Choose one:** is this a 🐛 bug report 

Running `inspec check` on a profile that has an incorrect name or a name which is not defined in `inspec.yml` leads to the following error:

```
NoMethodError: undefined method `profile' for nil:NilClass
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/dsl.rb:60:in `load_spec_files_for_profile'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/dsl.rb:16:in `include_controls'
  /tmp/foo/controls/example.rb:4:in `load_with_context'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:160:in `instance_eval'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:160:in `load_with_context'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:144:in `load_control_file'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:195:in `block in collect_tests'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:192:in `each'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:192:in `collect_tests'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:588:in `load_checks_params'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:581:in `load_params'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:184:in `params'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:435:in `controls_count'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile.rb:406:in `check'
  /home/jerry/Projects/github.com/inspec/inspec/lib/inspec/cli.rb:86:in `check'
  /home/jerry/.gem/ruby/2.4.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/jerry/.gem/ruby/2.4.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/jerry/.gem/ruby/2.4.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/jerry/.gem/ruby/2.4.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/jerry/Projects/github.com/inspec/inspec/bin/inspec:12:in `<top (required)>'
  /home/jerry/.gem/ruby/2.4.3/bin/inspec:23:in `load'
  /home/jerry/.gem/ruby/2.4.3/bin/inspec:23:in `<top (required)>'
```

### 🤔 Replication Case

```
inspec init profile /tmp/example
echo "include_controls 'bad name'" > /tmp/example/controls/example.rb
inspec check /tmp/example
```

### 💁 Possible Solutions

Prevent this error and raise a more descriptive one.

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This changes the error message from using a bad reference in
`include_controls` from:

```
NoMethodError: undefined method `profile' for nil:NilClass
```

To one detailing that the profile cannot be loaded since it isn't listed
as a dependency.

This closes #3769.

### CODE REVIEW

File: test/functional/inspec_check_test.rb [hunk 1]
```diff
@@ -88,6 +88,15 @@
...
-    end    
+    end
+  end
+
+  describe 'inspec check with invalid `include_controls` reference' do
+    it 'raises an error matching /Cannot load \'invalid_name\'/' do
+      invalid_profile = File.join(profile_path, 'invalid-include-controls')
+      out = inspec('check ' + invalid_profile)
+      out.exit_status.must_equal 1
+      out.stderr.must_match /Cannot load 'invalid_name'/
```
Comment (clintoncwolfe) [inline test/functional/inspec_check_test.rb]: I'd like to check for the string 'is not listed as a dependency' in the error message, since that is main concern of this change.

File: test/unit/mock/profiles/invalid-include-controls/README.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+# Invalid Include Controls
+
+This profile contains an `include_controls` line with a invalid reference
```
Comment (clintoncwolfe) [inline test/unit/mock/profiles/invalid-include-controls/README.md]: Personally, I prefer to delete the README (which is optional) and place the description of the test profile in the profile metadata (which is "less optional").

File: test/unit/mock/profiles/invalid-include-controls/controls/example.rb [hunk 3]
```diff
@@ -0,0 +1,4 @@
+# encoding: utf-8
+# copyright: 2018, The Authors
+
+include_controls 'invalid_name'
```
Comment (clintoncwolfe) [inline test/unit/mock/profiles/invalid-include-controls/controls/example.rb]: Not a big deal, but you might consider 'no_such_profile' (or similar) rather than 'invalid_name' - directly communicate what is being tested. (There is nothing invalid about 'invalid_name' - you could have a profile named that.)

**Review by clintoncwolfe — COMMENTED** [review]
A few thoughts on testing, but nothing to block the merge.

File: test/functional/inspec_check_test.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply test/functional/inspec_check_test.rb]: I can add another line 👍

File: test/unit/mock/profiles/invalid-include-controls/README.md (hunk 2 above)
Comment (jerryaldrichiii) [reply test/unit/mock/profiles/invalid-include-controls/README.md]: I agree on both, been a while since I've created one of these.

File: test/unit/mock/profiles/invalid-include-controls/controls/example.rb (hunk 3 above)
Comment (jerryaldrichiii) [reply test/unit/mock/profiles/invalid-include-controls/controls/example.rb]: Nope, solid feedback. I couldn't find a good name. Will use `no_such_profile`.

**Review by clintoncwolfe — APPROVED** [review]
Thanks, @jerryaldrichiii!

**Review by miah — APPROVED** [review]
