### PR TITLE
Fix archive with required attributes

### LINKED ISSUE #3464: Cannot archive profile when attributes have no default attribute
### 🎛 Description

this a 🐛 bug report

When using unified attributes (I think applies to normal attribute behaviour too, but not tested) without default values, and required, the profile cannot be archived with `inspec archive` 

Use https://github.com/dev-sec/cis-dil-benchmark/pull/55 and change the inspec.yml to match (no default value provided)

```yml
attributes:
  - name: cis_level
    required: true
    description: 'CIS profile level to audit'
    type: numeric
```

Then InSpec returns the following error

```bash
$ inspec archive cis-dil-benchmark
Attribute 'cis_level' is required and does not have a value.
```

### 🌍 InSpec and Platform Version

InSpec 2.3.8 (3248af1f)

### 🤔 Replication Case

As described above.

### 💁 Possible Solutions

ignore missing attributes when used in archive mode 

### 💻 Stacktrace

n/a

### PR DESCRIPTION
**Pull request by jquick**
This allows profiles to be vendored and archived when they have required attributes.

Fixes #3464

### CODE REVIEW

**Review by miah — APPROVED** [review]

File: lib/inspec/objects/attribute.rb [hunk 1]
```diff
@@ -89,6 +89,9 @@ def to_s
     private
 
     def validate_required(value)
+      # skip if we are not doing a exec (archive/vendor)
```
Comment (jerryaldrichiii) [inline lib/inspec/objects/attribute.rb]: Should be `an exec`, I also think the below is easier to understand but I'll leave that to you:

```
# Skip if we are using `inspec exec` (`inspec archive/vendor` is okay)

**Review by jerryaldrichiii — CHANGES_REQUESTED** [review]

File: lib/inspec/objects/attribute.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply lib/inspec/objects/attribute.rb]: Whoops...I got this backwards. You've got it right.

**Review by jerryaldrichiii — APPROVED** [review]
