### PR TITLE
Fix and document registry issues

### LINKED ISSUE #1131: Strange `registry_key` behavior (Unable to get .NET Version)
#### Intended Goal

I am attempting to get the following test to pass:

``` ruby
describe registry_key('HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/NET Framework Setup/NDP/v4/Full') do
  its('Release') { should eq 378_765 }
end
```
#### Problem

I can only get the value of `nil` for `Release`
#### More Info

Using `/` or placing an extra `\` somewhere in the path allows the tests below to pass...however it does not allow me to get the value of `Release`.

``` ruby
describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full') do
  it { should exist } # Fails
  its('Release') { should eq 378_765 } # Fails
end

describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Fu\ll') do
  it { should exist } # Passes (See `Full` above)
  its('Release') { should eq 378_765 } # Fails
end

describe registry_key('HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/NET Framework Setup/NDP/v4/Full') do
  it { should exist } # Passes
  its('Release') { should eq 378_765 } # Fails
end
```

Also, it appears cannot get the value of any key under `v4` but can under `v4.0`. See:

``` ruby
describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client') do
  its('Install') { should eq 1 } #Fails
end

describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0\Client') do
  its('Install') { should eq 1 } #Passes
end
```
### Picture of Registry

screen shot 2016-09-22 at 3 13 53 pm
### InSpec and Platform Version

InSpec Version: `0.29.0`
Platform: Windows 2012R2

### LINKED ISSUE #1268: Bug or doc problem with `registry_key`
### Description

http://inspec.io/docs/reference/resources/registry_key/ has this:

```
describe registry_key({
  name: 'Task Scheduler',
  hive: 'HKEY_LOCAL_MACHINE',
  key: ''\SYSTEM\CurrentControlSet\services\Schedule'
}) do
  its('Start') { should eq 2 }
end
```

The `key` clearly has an issue with the double single quote, but it seems to indicate that key path can start with a backslash.  But using a path like `\SYSTEM\CurrentControlSet\services\Schedule' will result in something like:

```
    expected: 1
          got: nil
```

### InSpec and Platform Version

```
inspec (1.3.0)
ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin13]
```

### Replication Case

A cookbook with `test/integration/default/inspec/default_spec.rb`:
```
describe registry_key({
    hive: 'HKEY_LOCAL_MACHINE',
    key:  'Software\Policies\Microsoft\Windows NT\Terminal Services'
  }) do
    its("fEncryptRPCTraffic") { should eq 1 }
end

describe registry_key({
    hive: 'HKEY_LOCAL_MACHINE',
    key:  '\Software\Policies\Microsoft\Windows NT\Terminal Services'
  }) do
    its("fEncryptRPCTraffic") { should eq 1 }
end
```

against win2012rs kitchen verify: 

```
-----> Verifying <default-windows-2012r2>...
       Detected alternative framework tests for `inspec`
       Use `/Users/peterburkholder/Projects/pburkholder/windows_stig_cookbook/test/integration/default/inspec` for testing

Target:  winrm://pburkholder@http://ec2-54-84-128-213.compute-1.amazonaws.com:5985/wsman:3389


  File c:/
     ✔  should exist
  Registry Key
     ✔  HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services fEncryptRPCTraffic should eq 1
  Registry Key
     ✖  HKEY_LOCAL_MACHINE\\Software\Policies\Microsoft\Windows NT\Terminal Services fEncryptRPCTraffic should eq 1

     expected: 1
          got: nil

     (compared using ==)


Test Summary: 2 successful, 1 failures, 0 skipped
```

### Possible Solutions

1. Allow leading backslash

2. Clarify the documentation

Which shall we do...??

### PR DESCRIPTION
**Pull request by chris-rock**
Powershell 3 has issues with some characters in strings when used in combination with `ConvertTo-Json`:

```
PS C:\Windows\system32> $properties = New-Object -Type PSObject
$properties | Add-Member "super" "\/value/\\"
$properties | ConvertTo-Json
ConvertTo-Json : The converted JSON string is in bad format.
At line:3 char:15
+ $properties | ConvertTo-Json
+               ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{super=\/value/\\}:PSObject) 
    [ConvertTo-Json], InvalidOperationException
    + FullyQualifiedErrorId : JsonStringInBadFormat,Microsoft.PowerShell.Comma 
   nds.ConvertToJsonCommand
```

By using `ConvertTo-Json -Compress`, it just works:
```
PS C:\Windows\system32> $properties = New-Object -Type PSObject
$properties | Add-Member "super" "\/value/\\"
$properties | ConvertTo-Json -Compress
{"super":"\\/value/\\\\"}
``` 

 * Fixes #1131
 * Fixes #1268
 * adds documentation for #1281

### CODE REVIEW

File: lib/resources/registry_key.rb [hunk 1]
```diff
@@ -66,7 +66,10 @@ def initialize(name, reg_key = nil)
         # generate registry_key if we do not have a regular expression
         @options[:path] = @options[:hive]
         # add optional key path
-        @options[:path] += '\\' + @options[:key] if @options[:key]
+        if @options[:key]
```
Comment (adamleff) [inline lib/resources/registry_key.rb]: Can we break out the building of the path to a private helper method in this class and add some tests to it? There's enough conditional logic in building the path now that I think it's warranted.

**Review by adamleff — CHANGES_REQUESTED** [review]

File: lib/resources/registry_key.rb (hunk 1 above)
Comment (chris-rock) [reply lib/resources/registry_key.rb]: I agree with you @adamleff This would increase the quality!

**Comment by chris-rock** [comment]
Thank you @adamleff for improving my PR.

**Review by adamleff — APPROVED** [review]
