### PR TITLE
Fix for warning when input is provided

### LINKED ISSUE #4445: Confusing warning message when input has no value
# Describe the problem

As reported [here](https://github.com/inspec/inspec/issues/3802#issuecomment-526972910), if an input in the DSL does not have a value, the warning message can read:
```
WARN: Input 'cis_level' does not have a value. Use --input-file to provide a value for 'cis_level' or specify a value with attribute('cis_level', value: 'somevalue', ...)
```

Note that it uses the term `attribute(...)`, which is out of date.

### LINKED ISSUE #4769: Warns about no value for an input, although a value has been set
# Describe the problem

I created a test profile with this `inspec.yml` configuration:
```yaml
name: default
inputs:
  - name: foo
    type: numeric
    required: true

  - name: bar
    type: string
    required: true
```

I have a simple control which get the values of these (mandatory) inputs and asserts some values based on these inputs:
```ruby
foo = input('foo')
bar = input('bar')
...
# omitted but foo and bar are used
```

I have a input variable file with:

```yaml
foo: 42
bar: hello
```

When I ran InSpec, I get warnings about missing values for the inputs (+ the confusing message from #4445):

```
$ bundle exec inspec exec profile --input-file $PWD/test-inputs.yml 
[2019-12-06T14:17:14+01:00] WARN: Input 'foo' does not have a value. Use --input-file to provide a value for 'foo' or specify a  value with `attribute('foo', value: 'somevalue', ...)`.
[2019-12-06T14:17:14+01:00] WARN: Input 'bar' does not have a value. Use --input-file to provide a value for 'bar' or specify a  value with `attribute('bar', value: 'somevalue', ...)`.
...
```

See https://github.com/multani/inspec-issue-4769 for a demonstration of the problem.

### PR DESCRIPTION
**Pull request by clintoncwolfe**
## Description

Fixes some cases in which a profile may require inputs in its metadata but not provide a default value (a reasonable thing to do), causing InSpec to emit noisy warnings like:

```
[2020-02-07T16:33:50-05:00] WARN: Input 'hostname' does not have a value. Use --input-file to provide a value for 'hostname' or specify a value with attribute('hostname', value: 'somevalue', ...).
```

These warnings would be emitted even if the value was provided by `--input-file`.

The cause was traced to the validation routines requesting a value; the act of requesting a value would cause a warning to be emitted if one was not known. A parameter was added to make the check silent if it was only checking for a value, not trying to use one.

Additionally, the message emitted referred to inputs as attributes, which is deprecated; the message was updated.

A new test fixture was created, along with a pair of functional tests.

## Related Issue

Fixes #4769
Fixes #4445

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/input.rb [hunk 1]
```diff
@@ -98,15 +98,15 @@ def self.probe_stack
     # not been assigned a value. This allows a user to explicitly assign nil
     # to an input.
     class NO_VALUE_SET # rubocop: disable Naming/ClassAndModuleCamelCase
-      def initialize(name)
+      def initialize(name, obnoxiously_warn = true)
```
Comment (james-stocks) [inline lib/inspec/input.rb]: This param might be better named `strict_warn` or `warn_if_not_set` 
And/or describe it in the comment lines before the method

**Comment by james-stocks** [comment]
I left one comment just on parameter naming; otherwise this looks perfect, thanks @clintoncwolfe :)

**Comment by Schwad** [comment]
Yep same looks good to me! 😄

**Review by Schwad — APPROVED** [review]

**Review by james-stocks — APPROVED** [review]
Thanks a million @clintoncwolfe !

I tested this out with the common workflow of a base profile that does not give the input a value; a wrapper profile that inherits the input, then an `inputs.yml` file that finally provides a value for the input.

I get 2 pointless warnings from `master` and 0 from this branch :)

```
jstocks@phobos inspec % git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
jstocks@phobos inspec % bundle exec inspec exec ../../profiles/inputs_wrapper --input-file ../../profiles/inputs_wrapper/inputs.yml
[2020-05-01T14:22:58+01:00] WARN: Input 'api_key' does not have a value. Use --input-file to provide a value for 'api_key' or specify a  value with `attribute('api_key', value: 'somevalue', ...)`.
[2020-05-01T14:22:58+01:00] WARN: Input 'api_key' does not have a value. Use --input-file to provide a value for 'api_key' or specify a  value with `attribute('api_key', value: 'somevalue', ...)`.

Profile: InSpec Profile (inputs_wrapper)
Version: 0.1.0
Target:  local://

  RGKEGNKRNRKG
     ×  is expected to eq "ERGRGREGREEG"
     
     expected: "ERGRGREGREEG"
          got: "RGKEGNKRNRKG"
     
     (compared using ==)


Profile: InSpec Profile (inputs)
Version: 0.1.0
Target:  local://

     No tests executed.

Test Summary: 0 successful, 1 failure, 0 skipped
jstocks@phobos inspec % git checkout cw/late-warn-on-no-value                                                                      
Switched to branch 'cw/late-warn-on-no-value'
Your branch is up to date with 'origin/cw/late-warn-on-no-value'.
jstocks@phobos inspec % bundle exec inspec exec ../../profiles/inputs_wrapper --input-file ../../profiles/inputs_wrapper/inputs.yml

Profile: InSpec Profile (inputs_wrapper)
Version: 0.1.0
Target:  local://

  RGKEGNKRNRKG
     ×  is expected to eq "ERGRGREGREEG"
     
     expected: "ERGRGREGREEG"
          got: "RGKEGNKRNRKG"
     
     (compared using ==)


Profile: InSpec Profile (inputs)
Version: 0.1.0
Target:  local://

     No tests executed.

Test Summary: 0 successful, 1 failure, 0 skipped
jstocks@phobos inspec % 

```
