### PR TITLE
Fix alternate path profile chaining

### LINKED ISSUE #2120: Chained InSpec Profiles use the wrong base path
### Description

If a dependency path is specified in an `inspec.yml` file, any relative paths should be relative to the referencing `inspec.yml` file.

### InSpec and Platform Version

Version: 1.35.2

### Replication Case

During my spec tests, I separate out the inspec profiles and external dependencies into the following directories.

```
/tmp/inspec
├── inspec_deps
│   └── inspec_profiles
│       ├── profiles
│       │   ├── disa_stig-rhel7-baseline
│       │   │   ├── controls
│       │   │   ├── docs
│       │   │   │   └── source
│       │   │   │       └── U_Red_Hat_Enterprise_Linux_7_V1R1_Manual_STIG
│       │   │   ├── files
│       │   │   ├── inspec.yml
│       │   │   ├── libraries
│       │   │   │   └── profile_helper
│       │   │   ├── tmp_fold_in_to_controls
│       │   │   └── tools
│       │   └── simp_stig-rhel7
│       │       ├── controls
│       │       └── inspec.yml
└── inspec_profiles
    └── CentOS-7-disa_stig
        ├── controls
        └── inspec.yml
```

The bottom `inspec.yml` has the following content:

```yaml
depends:
  - name: simp_stig-rhel7
    path: ../../inspec_deps/inspec_profiles/profiles/simp_stig-rhel7
```

The referenced `simp_stig-rhel7.yml` has the following content:

```yaml
depends:
  - name: disa_stig-rhel7-baseline
    path: ../disa_stig-rhel7-baseline
```

### Possible Solutions

Any relative paths should be relative to the referencing `inspec.yml`, not the top level.

### Stacktrace

The error that I recieve when running `inspec exec` on the `/tmp/inspec_profiles/CentOS-7-disa_stig` directory is as follows:

```
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:71:in `read': No such file or directory @ rb_sysopen - /tmp/inspec/inspec_profiles/disa_stig-rhel7-baseline (Errno::ENOENT)
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:71:in `sha256'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:65:in `cache_key'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:32:in `cache_key'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:39:in `fetch'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:22:in `resolved_source'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/requirement.rb:62:in `resolved_source'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:80:in `block in resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:31:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/profile.rb:393:in `generate_lockfile'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:110:in `write_lockfile'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:80:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:78:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:78:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:99:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/base_cli.rb:83:in `run_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cli.rb:159:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/bin/inspec:12:in `<top (required)>'
        from /bin/inspec:23:in `load'
        from /bin/inspec:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Update to fix how multiple relative profile chaining functions.

Closes #2120

### CODE REVIEW

File: lib/inspec/dependencies/requirement.rb [hunk 1]
```diff
@@ -10,7 +10,18 @@ module Inspec
   class Requirement
     def self.from_metadata(dep, cache, opts)
       raise 'Cannot load empty dependency.' if dep.nil? || dep.empty?
-      new(dep[:name], dep[:version], cache, opts[:cwd], opts.merge(dep))
+
+      req_path = opts[:cwd]
+
+      if dep[:path]
+        req_path = File.join(req_path, dep[:path])
```
Comment (adamleff) [inline lib/inspec/dependencies/requirement.rb]: I think this will only work if the `path` in the requirement is a relative path. What if I have an absolute path in my metadata?

```yaml
depends:
  - name: foo
    path: '/path/to/foo'
```

If my cwd is `/home/aleff/profiles`, this would set the `req_path` to `/home/aleff/profiles/path/to/foo` which won't exist... correct?

You probably want to look into using `File.expand_path` here instead which handles both relative and absolute path expansion.

```
[1] pry(main)> Dir.pwd
=> "/Users/aleff/profiles/test1"
[2] pry(main)> File.expand_path('../test2', Dir.pwd)
=> "/Users/aleff/profiles/test2"
[3] pry(main)> File.expand_path('/opt/chef/embedded', Dir.pwd)
=> "/opt/chef/embedded"
```

**Review by adamleff — CHANGES_REQUESTED** [review]
Thanks for the PR, @trevor-vaughan! Unfortunately I don't think it will work for absolute paths in dependencies. I've left you a comment with a potential alternate solution that you should test to see if it meets the needs of the issue you're trying to solve. Thanks!

**Comment by trevor-vaughan** [comment]
@adamleff Good call. Fixed

File: lib/inspec/dependencies/requirement.rb [hunk 2]
```diff
@@ -10,7 +10,18 @@ module Inspec
...
+      req_path = opts[:cwd]
+
+      if dep[:path]
+        req_path = File.expand_path(dep[:path], req_path)
+      end
+
+      new(dep[:name],
+          dep[:version],
+          cache,
+          File.absolute_path(req_path),
```
Comment (adamleff) [inline lib/inspec/dependencies/requirement.rb]: `File.expand_path` [here](https://github.com/chef/inspec/pull/2121/files#diff-c31bbcc4f73daa9c1b95020b03f5303dR17) should do the trick, right? We probably don't even need to call on `File.absolute_path` anymore.

Comment (trevor-vaughan) [reply lib/inspec/dependencies/requirement.rb]: Heh, completely missed that. Updated.

**Review by adamleff — APPROVED** [review]
This looks good to me, @trevor-vaughan, thanks!

In the future, we prefer it if you don't rebase/amend your commits each time as it helps us look at only the stuff that's changed between reviews. While it's not as big of a deal on this change since it's so small, it helps reduce the amount of time spent reviewing the PR on larger changes.

Thanks again for your contribution!

**Comment by trevor-vaughan** [comment]
@adamleff Got it, I'll keep that in mind in the future.

**Review by arlimus — APPROVED** [review]
Awesome catch and bugfix, thank you Trevor!! 😁
