### PR TITLE
Enhance `package` resource error handling

### LINKED ISSUE #1692: NilClass errors when package info fails
Appears to be a bug in the `package` resource if the command used to find the package details fails.

```
              1) System Package amazon-ssm-agent should be installed
                   Failure/Error: info[:installed] == true

                        NoMethodError:
                               undefined method `[]' for nil:NilClass
```

`info` should return an empty hash until we have better exception handling.

### LINKED ISSUE #2373: Package resource passes when no packages are defined
### Description

When describing a package and not defining a package name, the inspec test will pass.

### InSpec and Platform Version

Confirmed on 1.45.13, CentOS 6.5

### Replication Case

Create a package resource with no packages defined:

```
describe package do
  it { should be_installed }
end
```

```
System Package
✔ should be installed
```

### Possible Solutions

I think, this should fail or generate an error that "package name" is undefined for "package" control/resource

### Stacktrace

No stack trace as test passes.

Thanks!

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This does the following:
  - Modifies `info` to return an empty hash instead of `nil`
  - Adds a failure case if package name is not specified
  - Adds a skip case if no package manager can be found
  - Changes `skip_resource` to use the `ResourceSkipped` exception
  - Raises an error if JSON parsing fails for Windows/MacOS/Darwin

This closes #1692
This closes #2373

### CODE REVIEW

File: lib/resources/package.rb [hunk 1]
```diff
@@ -20,7 +20,9 @@ class Package < Inspec.resource(1)
       end
     "
 
-    def initialize(package_name = nil, opts = {}) # rubocop:disable Metrics/AbcSize
+    def initialize(package_name = nil, opts = {}) # rubocop:disable Metrics/AbcSize, Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity
```
Comment (adamleff) [inline lib/resources/package.rb]: Maybe we should change this to:

```ruby
def initialize(package_name, opts = {})
```

... such that Ruby enforces that `package_name` must be specified? While I agree that the error message isn't as clear as the one you've provided, we should be consistent with other resources that have required parameters. 

We can always add some arity magic in the future with better error messaging, but for now, we should be consistent.

File: lib/resources/package.rb [hunk 2]
```diff
@@ -45,36 +47,32 @@ def initialize(package_name = nil, opts = {}) # rubocop:disable Metrics/AbcSize
       elsif ['hpux'].include?(os[:family])
         @pkgman = HpuxPkg.new(inspec)
       else
-        return skip_resource 'The `package` resource is not supported on your OS yet.'
+        raise Inspec::Exceptions::ResourceSkipped, 'The `package` resource is not supported on your OS yet.'
```
Comment (adamleff) [inline lib/resources/package.rb:48]: Thanks for this - in the same vein as my prior comment, since we're adopting exceptions as the new normal, moving toward that is a good thing.

File: lib/resources/package.rb [hunk 3]
```diff
@@ -45,36 +47,32 @@ def initialize(package_name = nil, opts = {}) # rubocop:disable Metrics/AbcSize
...
     # returns true if the package is installed
     def installed?(_provider = nil, _version = nil)
-      return false if info.nil?
       info[:installed] == true
     end
 
     # returns true it the package is held (if the OS supports it)
     def held?(_provider = nil, _version = nil)
-      return false if info.nil?
       return false unless info.key?(:held)
```
Comment (adamleff) [inline lib/resources/package.rb]: I think we can remove this too and just it fall through to the boolean comparison, yes?

**Review by adamleff — CHANGES_REQUESTED** [review]
This looks like some good cleanup, @jerryaldrichiii - just a couple of comments.

File: lib/resources/package.rb (hunk 3 above)
Comment (jerryaldrichiii) [reply lib/resources/package.rb]: Yup, I see we set it to a bool farther down. Good catch!

**Review by adamleff — APPROVED** [review]
Thanks for this improvement, @jerryaldrichiii.

**Review by arlimus — APPROVED** [review]
Fantastic improvement, thank you Jerry!
