### PR TITLE
service resource: attempt a SysV fallback if SystemD unit file is not found

### LINKED ISSUE #1708: systemctl is-enabled fails on Debian for SysV units
### Description

On Debian 8, a SysV unit (such as the stock `apache2` package) will fail the `systemctl is-enabled` command because Debian 8's systemd doesn't include the `systemd-sysv-install` shim.

### InSpec and Platform Version

1.19.1

### Replication Case

**recipe:**

```ruby
package 'apache2'

service 'apache2' do
  action :enable
end
```

**test:**

```ruby
describe service('apache2') do
  it { should be_enabled }
end
```

**inspec output:**

```
  Service apache2
     ∅  should be enabled
     expected that `Service apache2` is enabled
```

**manual command run:**

```
root@default-debian-87:~# systemctl is-enabled apache2
Failed to get unit file state for apache2.service: No such file or directory
root@default-debian-87:~# echo $?
1
```

### Possible Solutions

It would be great if InSpec could detect this failure and try the init script in `/etc/init.d` as a fallback.

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This modifies the `enabled?` check to fallback to `sysv_service` in the event that a `.service` file cannot be found.

For example: On Debian 8.7 the stock apache2 package does not deploy a `.service` file but deploys a SysV style service. This causes `systemctl is-enabled` to fail when the service is in fact enabled.

This closes #1708

### CODE REVIEW

File: test/helper.rb [hunk 1]
```diff
@@ -195,6 +195,11 @@ def md.directory?
       mock.mock_command('', '', '', 0)
     }
 
+    cmd_stderr = lambda { |x|
+      stderr = ::File.read(::File.join(scriptpath, '/unit/mock/cmd/'+x))
```
Comment (adamleff) [inline test/helper.rb]: We don't need to do string concatenation or interpolation when we're already in a `File.join` call. It's also customary to remove the leading and trailing slashes and let `File.join` do its thing:

```ruby
stderr = ::File.read(::File.join(scriptpath, 'unit/mock/cmd', x))
```

I also question whether we really need another helper here, especially when this is also doing an `exit 1` like `cmd_exit_1` is already doing. Should we just enhance `cmd_exit_1` to accept an optional path to stderr output?

**Review by adamleff — CHANGES_REQUESTED** [review]
Functionally looks good, @jerryaldrichiii. I think we can cleanup the test helper before merging though.

File: test/helper.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply test/helper.rb]: I agree with all those points! Update incoming.

Thanks for your always stellar reviews!

File: test/helper.rb [hunk 2]
```diff
@@ -195,13 +195,11 @@ def md.directory?
       mock.mock_command('', '', '', 0)
     }
 
-    cmd_stderr = lambda { |x|
-      stderr = ::File.read(::File.join(scriptpath, '/unit/mock/cmd/'+x))
-      mock.mock_command('', '', stderr, 1)
+    cmd_exit_1 = lambda { |x = nil|
+      stderr = ::File.read(::File.join(scriptpath, 'unit/mock/cmd', x)) if x
```
Comment (adamleff) [inline test/helper.rb]: You might think I'm nitpicking here, but I think we can eliminate the conditional in the following line and just let `stderr` always be the right thing (rather than `mock_command` having another in-line conditional):

```ruby
stderr = x.nil? ? '' : ::File.read(::File.join(scriptpath, 'unit/mock/cmd', x))
mock.mock_command('', '', stderr, 1)
```

That's a bit more direct and clear, would you agree?

**Review by adamleff — CHANGES_REQUESTED** [review]

File: test/helper.rb (hunk 2 above)
Comment (jerryaldrichiii) [reply test/helper.rb]: Yup, I agree, elegant use of the ternary. Not nitpicky at all! 😄

**Review by adamleff — APPROVED** [review]
LGTM, @jerryaldrichiii - thanks!

**Review by arlimus — APPROVED** [review]
Great handling of a corner-case, love the fallback @jerryaldrichiii thank you!

**Comment by tas50** [comment]
@jerryaldrichiii You've solved my #1 inspec bug. Thanks
