### PR TITLE
Move Passthrough Config from Automate to JSON Reporter

### LINKED ISSUE #3181: Allow pass-through metadata in reports
### 🎛 Description

Many users have reported the requirement to pass-through additional metadata about the node via the report to map the data later to existing system identifier in other systems.

We already added specific metadata to the automate reporter that is passing through `nodename`, ` nodeid`, `environment`, `reportuuid` and `jobuuid` by using our json config to pass-through data:

```bash
#!/bin/bash
cat options.json | sudo inspec exec examples/simple --json-config=-
```

where `options.json` could look like:
```json
{
    "sudo" : true,
    "reporter" : {
        "json": {},
        "automate" : {
            "url": "http://example.com",
            "token" : "abctoken",
            "nodename" : "nodename",
            "nodeid" : "nodeid",
            "environment": "envname",
            "reportuuid" : "reportid",
            "jobuuid" :"jobid"
        }
    }
}
```

This mechanism is not available for all reporters as pointed out in #2966. In addition it is very inflexible for further extension.

### 💁 Possible Solutions

In order to simplify the the approach and to cover more needs I propose we are adding `tags` to the json config that are passed-through to the `json` and `automate` reporter.  At this point, we are not adding this capability to the `json-min` or other reporters. The following config includes a new `tags` map of type `map[string]string`:

```json
{
    "sudo" : true,
    "reporter" : {
        "json": {}
    },
    "tags" : {
        "key" : "value",
        "key2" : "value2",
    }
}
```

The following tags are added implicitly via InSpec if they are not already provided by the pass-through tags:
```
    "tags" : {
        "nodename" : "myhostname",
        "nodeid" : "36D92FEE-D3AF-43FE-902A-7D9113533322",
        "reportuuid" : "BDCAA363-51F9-4A2E-A174-97E1059B85E8",
    }
```

Which leads to the following json report:

```json
{
  "platform": {
    "name": "mac_os_x",
    "release": "17.6.0"
  },
  "tags" : {
        "key" : "value",
        "key2" : "value2",
        "nodename" : "myhostname",
        "nodeid" : "36D92FEE-D3AF-43FE-902A-7D9113533322",
        "reportuuid" : "BDCAA363-51F9-4A2E-A174-97E1059B85E8",
   },
  "profiles": [
    {
      "name": "simple",
      "version": "1.0.0",
      "sha256": "0b616e1cd91e754515a786357e44376e72a0f787d6a31f58f6a2bf867e7ff0cb",
      "title": "InSpec Example Profile",
      "maintainer": "Chef Software, Inc.",
      "summary": "Demonstrates the use of InSpec Compliance Profile",
      "license": "Apache-2.0",
      "copyright": "Chef Software, Inc.",
      "copyright_email": "support@chef.io",
      "supports": [
        {
          "os-family": "unix"
        }
      ],
      "attributes": [],
      "groups": [
        {
          "id": "controls/example.rb",
          "controls": [
            "tmp-1.0"
          ],
          "title": "/tmp profile"
        }
      ],
      "controls": [
        {
          "id": "tmp-1.0",
          "title": "Create /tmp directory",
          "desc": "An optional description...",
          "impact": 0.7,
          "refs": [
            {
              "url": "http://...",
              "ref": "Document A-12"
            }
          ],
          "tags": {
            "data": "temp data",
            "security": null
          },
          "code": "control \"tmp-1.0\" do                        # A unique ID for this control\n  impact 0.7                                # The criticality, if this control fails.\n  title \"Create /tmp directory\"             # A human-readable title\n  desc \"An optional description...\"         # Describe why this is needed\n  tag data: \"temp data\"                     # A tag allows you to associate key information\n  tag \"security\"                            # to the test\n  ref \"Document A-12\", url: 'http://...'    # Additional references\n\n  describe file('/tmp') do                  # The actual test\n    it { should be_directory }\n  end\nend\n",
          "source_location": {
            "line": 7,
            "ref": "examples/simple/controls/example.rb"
          },
          "results": [
            {
              "status": "passed",
              "code_desc": "File /tmp should be directory",
              "run_time": 0.001744,
              "start_time": "2018-06-28T10:46:54+02:00"
            }
          ]
        }
      ]
    }
  ],
  "statistics": {
    "duration": 0.003056
  },
  "version": "2.1.81"
}



```

### 🌍 InSpec and Platform Version

InSpec 2.x

### 🤔 Replication Case

N/A

### 💻 Stacktrace

N/A

Aha! Link: https://chef.aha.io/features/SH-452

### PR DESCRIPTION
**Pull request by tohch4**
## Description
This with meet requirements for #3181 to generalize `passthrough` parameter in configuration so it works for JSON reporters, not specifically the Automate reporter only, based on comments and feedback in that issue.

## Related Issue

Resolves inspec/inspec#3181.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [X] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.

CC @aaronlippold @rbclark

### CODE REVIEW

**Comment by tohch4** [comment]
I would love feedback from the core maintainers, as I had test failures when running the whole test suite locally for all tests, but those seem in no way related to the parts of the code base I modified. If I also need to complete this feature change with documentation, let me know, I will move it forward.

**Comment by aaronlippold** [comment]
@tohch4 yes, documentation will need to be updated. I believe @clintoncwolfe just added a PR to update the docs for the 'json-automate' reporter. We could borrow from that as we update the 'cli' documentation for the new flag, example input to the feature etc.

**Comment by clintoncwolfe** [comment]
The verify tests are failing due to linting - please run "bundle exec chefstyle -a" to autocorrect the trailing whitespace errors.

File: test/functional/inspec_exec_automate_test.rb [hunk 1]
```diff
@@ -55,11 +55,7 @@
               "job_uuid": "test123",
               "roles": ["stuff"],
               "environment": "prod",
-              "node_name": "some_node",
-              "passthrough": {
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_automate_test.rb:59]: Must we remove this? Chef relies pretty heavily on having the passthrough data work with the json-automate reporter, so having it explicitly tested with this structure is desirable.

File: test/functional/inspec_exec_automate_test.rb [hunk 2]
```diff
@@ -90,11 +86,6 @@
         _(json.keys).wont_include field
       end
 
-      # Added in InSpec v3.7.11+
-      _(json.keys).must_include "passthrough"
-      _(json["passthrough"].keys.sort).must_equal %w{another_tramp_datum projects}
-      _(json["passthrough"]["projects"]).must_equal %w{alpha beta}
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_automate_test.rb]: As above, I'd like to see this kept in, if possible.

File: test/functional/inspec_exec_automate_test.rb (hunk 1 above)
Comment (tohch4) [reply test/functional/inspec_exec_automate_test.rb:59]: I assume it will work because of how the class inheritance with the tests, let me take care of that.

**Comment by tohch4** [comment]
Also @clintoncwolfe, you will want the docs updated to match this change in this PR or a separate PR? I have been unable to find what Aaron is referencing thus far.

**Comment by clintoncwolfe** [comment]
Yes, please update the docs on this PR - update the file docs-chef-io/content/inspec/reporters.md . Thanks!

**Comment by aaronlippold** [comment]
@tohch4 did we also update the Thor cli to have a `--passthrough` field?

Thanks

**Comment by aaronlippold** [comment]
cicd this I must ...

**Comment by tohch4** [comment]
> @tohch4 did we also update the Thor cli to have a `--passthrough` field?

I thought we agreed to just leave it as part of the `--config` porcelain for now as it is just another part of the JSON struct. Did I misunderstand?

**Comment by aaronlippold** [comment]
I would say we could reuse the `--input-files` code as a reference - having a `cli` path and a `file` path seems to be our standard which I would like to uphold.

**Comment by aaronlippold** [comment]
Looks like you also need to `git commit --amend -s` your branch as well to sign your PR

**Comment by clintoncwolfe** [comment]
Wait a sec, I'm OK with this as-is without a CLI option. Adding a CLI option seems like a different concept entirely and something worthy of discussion and debate. If you're going to do that, please do so on a separate PR so we can explore how it looks and feels.

**Review by clintoncwolfe — APPROVED** [review]
Thank you!

**Comment by tohch4** [comment]
So when can we expect this to move into official releases @clintoncwolfe? Do you document your release cutting policy for community contributions somewhere?

File: docs-chef-io/content/inspec/reporters.md [hunk 3]
```diff
@@ -101,7 +101,23 @@ This is the basic text base report. It includes details about which tests passed
 
 ### json
 
-This reporter includes all information about the profiles and test results in standard json format.
+This reporter includes all information about the profiles and test results in standard json format. You may optionally pass through arbitrary structured JSON data via a json config with the `--config` parameter like the example below.
+
+Example config:
+
```
Comment (IanMadd) [inline docs-chef-io/content/inspec/reporters.md]:
```suggestion
This reporter includes all information about the profiles and test results in standard JSON format. You may optionally pass through arbitrary structured JSON data by setting a JSON configuration with the `--config` parameter. 

For example:

```

Comment (tohch4) [reply docs-chef-io/content/inspec/reporters.md]: That's fine with me @IanMadd. Committed and back to you for final review!

Comment (tohch4) [reply docs-chef-io/content/inspec/reporters.md]: Also updated sign-off for DCO. I guess don't use the Github UI if you care about that for Chef review process! 😆

**Comment by clintoncwolfe** [comment]
This will go out in the next release, which typically happens on Wednesdays.
