### PR TITLE
Fix tags processing issue in profiles

### LINKED ISSUE #5631: Inspec 4.41 breaks tag processing
Processing of arrays in tags is broken as of 4.41

# Describe the problem

While testing on EL7, prior to using the inspec 4.41.2-1 RPM, [tags containing array items](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-71849.rb#L65) worked properly.

As of the 4.41.2 RPM, this syntax is now considered a syntax error.

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

Fixe tags processing issues in profiles
## Description

- Fix tags processing in profiles
- Fix control tags fetching logic which was breaking profiles with tags used in them
- **Small doc change related to tags filtering, maybe we can skip doc review for this since it is not a big doc change.**

## Related Issue

Fixes #5631 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: test/fixtures/profiles/control-tags/controls/example.rb [hunk 1]
```diff
@@ -1,8 +1,16 @@
...
   tag severity: nil
   tag data: "tag2"
   tag data_arr: ["tag3", "tag4"]
+  tag error1: "Line with a line-feed
+  error"
+  tag error2: "Line with a comma,error"
+  tag cci: ['CCI-000366']
+  tag legacy: []
+  tag nist: ["AU-9", "AU-9 (3)", "AC-3 (4)", "AC-6 (10)"]
+  tag ref: "http:example.html:CIS CSC v6.0 #5.1;"
```
Comment (aaronlippold) [inline test/fixtures/profiles/control-tags/controls/example.rb:13]: technically tag ref is not how ref is supported to be used.

```
  ref 'NSA-RH6-STIG - Section 3.5.2.1', url: 'https://www.nsa.gov/ia/_files/os/redhat/rhel5-guide-i731.pdf'

  ref 'happy day happy day'

ref 'https://www.chef.io'

``

File: lib/inspec/control_eval_context.rb [hunk 2]
```diff
@@ -53,19 +53,26 @@ def profile_name
...
-      tag_source = tag_source.map { |src| src.sub("tag", "").strip }.map { |src| src.split(",").map { |final_src| final_src.sub(/([^:]*):/, "") } }.flatten
-      output = tag_source.map { |src| src.sub(/\[|\]/, "") }.map { |src| instance_eval(src) }
-      output.compact.uniq
+    def control_tags(inspec_rule)
+      all_tags = []
+      inspec_rule.tag.each do |key, value|
+        all_tags.push(key)
+        all_tags.push(value) unless value.nil?
+      end
+      all_tags.flatten.compact.uniq.map(&:to_s)
```
Comment (aaronlippold) [inline lib/inspec/control_eval_context.rb:75]: Does this account for childern in a dependant profile? i.e. is the inherance alrealy accounted for at this point. Will this work with a wrapper profile or a dependant profile?

Comment (clintoncwolfe) [reply lib/inspec/control_eval_context.rb:75]: Thanks for catching that, we'll address that separately.

**Review by clintoncwolfe — APPROVED** [review]
