### PR TITLE
Fix windows plugin functional tests

### LINKED ISSUE #4700: Fix windows tests in test/functional/plugins_test.rb
test/functional/plugins_test.rb
```
326-    it "can run inspec shell and read a file" do
327-      outcome = inspec_with_env("shell -t test-fixture:// -c 'file(\"any-path\").content'", INSPEC_CONFIG_DIR: File.join(config_dir_path, "train-test-fixture"))
328:      skip_windows!
329-      _(outcome.stdout.chomp).must_equal "Lorem Ipsum"
330-
--
337-      outcome = inspec_with_env("shell -t test-fixture:// -c 'command(\"echo hello\").exit_status'", INSPEC_CONFIG_DIR: File.join(config_dir_path, "train-test-fixture"))
338-
339:      skip_windows!
340-      _(outcome.stdout.chomp).must_equal "17"
341-
```

### PR DESCRIPTION
**Pull request by clintoncwolfe**
Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>

## Description

Un-skips 2 tests, fixes a quoting issue in 3 places, and adds an explanatory comment in 2.

## Related Issue

Fixes #4700 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by miah — CHANGES_REQUESTED** [review]
Awesome. Thank you!

**Review by miah — APPROVED** [review]

File: test/functional/plugins_test.rb [hunk 1]
```diff
@@ -324,8 +324,9 @@ def run_input_plugin_test_with_controls(controls)
     end
 
     it "can run inspec shell and read a file" do
-      outcome = inspec_with_env("shell -t test-fixture:// -c 'file(\"any-path\").content'", INSPEC_CONFIG_DIR: File.join(config_dir_path, "train-test-fixture"))
-      skip_windows!
+      # The test fixture always returns the same content regardless of path
+      outcome = inspec_with_env("shell -t test-fixture:// -c 'file(%q{/opt/any-path}).content'", INSPEC_CONFIG_DIR: File.join(config_dir_path, "train-test-fixture"))
```
Comment (zenspider) [inline test/functional/plugins_test.rb:328]: nice

**Review by zenspider — APPROVED** [review]
