### PR TITLE
Make the --no-color flag work for inspec exec

### LINKED ISSUE #1024: --no-color switch not working when invoked with "inspec exec"
### Description

the --color/--no-color switch is not working when invoked with inspec exec.
It outputs in color anyway.
### InSpec and Platform Version

CentOS Linux release 7.2.1511 (Core)

Inspec versions 0.32.0, 0.33.0
### Replication Case

Run:

```
inspec exec test.rb --no-color
```

Result: the printed output in terminal is still colored.
### Possible Solutions

None.
### Stacktrace

None.

### PR DESCRIPTION
**Pull request by adamleff**
The CLI formatter is not currently honoring the --no-color flag
when outputting CLI output. This change cleans up how we format
with color and properly support the flag for use cases where
color-encoding characters make the output difficult to use
(i.e. when someone redirects CLI output to a text file for
sharing with others).

I also added the 'm' gem to the `test` group in the Gemfile, a
super-handy gem for running the minitest tests in a single file,
or a single test in a file.

Fixes #1024

### CODE REVIEW

File: lib/inspec/rspec_json_formatter.rb [hunk 1]
```diff
@@ -586,43 +585,54 @@ def print_anonymous_control(control)
...
+    output.puts(format_with_color(fields[:color], format_line(fields)))
   end
 
   # Helps formatting summary lines (called from within print_line arguments)
   def format_lines(lines, indentation)
     lines.gsub(/\n/, "\n" + indentation)
   end
 
+  def format_with_color(color_name, text)
+    return text unless RSpec.configuration.color
```
Comment (chris-rock) [inline lib/inspec/rspec_json_formatter.rb:630]: Is there any reason we are going to support this?

File: Gemfile [hunk 2]
```diff
@@ -20,6 +20,7 @@ group :test do
   gem 'ruby-progressbar', '~> 1.8'
   gem 'webmock', '~> 2.3.2'
   gem 'jsonschema', '~> 2.0.2'
+  gem 'm'
```
Comment (chris-rock) [inline Gemfile:23]: any reason why we need that?

File: lib/inspec/rspec_json_formatter.rb (hunk 1 above)
Comment (adamleff) [reply lib/inspec/rspec_json_formatter.rb:630]: This is currently what passing `--no-color` modifies to indicate the user's intent to not use color. There is also no other way to pass data (other than profiles) all the way down to the formatter, so I think this is a reasonable approach for this iteration.

File: Gemfile (hunk 2 above)
Comment (adamleff) [reply Gemfile:23]: I explained my intention in the PR message. This is a super easy way to run a single minitest test file, or even a single test in a file. If you don't want it in there, that's fine, but it makes for a better dev experience.

File: lib/inspec/rspec_json_formatter.rb (hunk 1 above)
Comment (chris-rock) [reply lib/inspec/rspec_json_formatter.rb:630]: Okay, makes sense. Its time to make reporting independent or RSpec. Nothing we can solve in that PR though.

File: Gemfile (hunk 2 above)
Comment (chris-rock) [reply Gemfile:23]: Those who are able to read are at an advantage indeed :-)

Comment (chris-rock) [reply Gemfile:23]: Can we add docs in our readme for that? Next time, I would prefer to have such things in separate PRs. No big deal though.

**Review by chris-rock — APPROVED** [review]
Quick turnaround. Awesome work @adamleff
