### PR TITLE
CFINSPEC-156 Oracle query fix when empty result

### LINKED ISSUE #5932: `oracledb_session` need to handle zero rows or empty output for select query.
# Describe the problem
Facing issue on Inspec version : 4.52.9 while using oracledb_session in case where select query as zero or empty output.
```
[2] pry(#<Inspec::Rule>)> oracledb_session.query("SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS WHERE PRIVILEGE='CREATE ANY LIBRARY' AND GRANTEE NOT IN (SELECT USERNAME FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y') AND GRANTEE NOT IN (SELECT ROLE FROM DBA_ROLES WHERE ORACLE_MAINTAINED='Y')")
Inspec::Exceptions::ResourceFailed: Oracle query with errors: 

from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:67:in `rescue in query'
Caused by NoMethodError: undefined method `sub' for nil:NilClass
from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:119:in `parse_csv_result'
```
and this happens when inspec_cmd.stdout is empty as:
```
    65:       DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
    66:     rescue
    67:       raise Inspec::Exceptions::ResourceFailed, "Oracle query with errors: #{out}"
    68:     end
    69:   end
    70: end

[6] pry(#<#<Class:0x00007fb3edb9e710>>)> inspec_cmd.stdout
=> ""
[8] pry(#<#<Class:0x00007fb3edb9e710>>)> DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
NoMethodError: undefined method `sub' for nil:NilClass
from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:119:in `parse_csv_result'
````
In older version of inspec the output for below controls was getting as empty now it's giving us the error.
control:
```
          describe oracledb_session.query("SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS WHERE PRIVILEGE='CREATE ANY LIBRARY' AND GRANTEE NOT IN (SELECT USERNAME FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y') AND GRANTEE NOT IN (SELECT ROLE FROM DBA_ROLES WHERE ORACLE_MAINTAINED='Y')") do
            it { should be_empty }
          end
```
## Possible Solution

We need to handle empty string scenario here example something like this `DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout)) unless inspec_cmd.stdout.empty?`or more appropriate
the solution gives us an `nil` output we should get output as `empty` all previously developed controls would not affect.

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

## Description

Oracle query fix when empty result
## Related Issue

Fixes #5932 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/oracledb_session.rb [hunk 1]
```diff
@@ -61,9 +61,13 @@ def query(sql)
         raise Inspec::Exceptions::ResourceFailed, "Oracle query with errors: #{out}"
       else
         begin
-          DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
-        rescue
-          raise Inspec::Exceptions::ResourceFailed, "Oracle query with errors: #{out}"
+          unless inspec_cmd.stdout.empty?
+            DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
+          else
```
Comment (clintoncwolfe) [inline lib/inspec/resources/oracledb_session.rb:66]: unless-else 💯

**Review by clintoncwolfe — APPROVED** [review]
Thanks!
