### PR TITLE
Remove default port for mssql_session, allowing named connections

### LINKED ISSUE #5548: MSSQL Named Instances doesn't work with current code
This issue is here for almost 2 years.
Named instances will not work without port. And MSSQL is capable of established that connection.

you can find the fix:
https://github.com/da3210/inspec/blob/dc/fixmssqlsession/lib/inspec/resources/mssql_session.rb

could you do a PR?

_Originally posted by @da3210 in https://github.com/inspec/inspec/issues/4319#issuecomment-852022224_

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

MSSQL resource fix for named instances (used with no port)
## Description

In current code, the default port was 1433 and so named instances had issue running without any port. So this change will enable using named instances without any port as well.
## Related Issue

Fixes #5548 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/mssql_session.rb [hunk 1]
```diff
@@ -42,11 +42,7 @@ def initialize(opts = {})
       @local_mode = opts[:local_mode]
       unless local_mode?
         @host = opts[:host] || "localhost"
-        if opts.key?(:port)
-          @port = opts[:port]
-        else
-          @port = "1433"
-        end
+        @port = opts[:port]
```
Comment (clintoncwolfe) [inline lib/inspec/resources/mssql_session.rb:45]: What happens if someone neither specifies a port nor uses a named connection? In that case, shouldn't we default to a port?

Comment (Nik08) [reply lib/inspec/resources/mssql_session.rb:45]: In that case also it works. It does not crash. MSSQL seems to establish connection even in that case. In my opinion it would work even without default port..but do you suggest we have the default port in case named instance is not used?

Comment (clintoncwolfe) [reply lib/inspec/resources/mssql_session.rb:45]: OK, if you've tested it without a port, it seems fine to me.
