### PR TITLE
Fix ObjectTraverser when accessing array values

### LINKED ISSUE #1560: json resource array index access not working
### Description

Currently trying to use the json resource. Array access via index is not working as described in the documentation.

I got the following json in test.json
```
{
  "hash":{
    "subhash":{
      "key": "value"
    }
  }
  "array": [
    "zero",
    "one",
    "three"
  ]
}
```
and the following control:
```
control 'test' do
  impact 1.0
  title 'test'
  desc '
   Test
  '

  describe file('/root/test.json') do
    it { should be_file }
  end

  describe json('/root/test.json') do
          its(['hash','subhash','key']) {should eq "value"}
          its(['array']) { should include "zero" }
          its(['array',0]) { should eq "zero" }
  end
end
```
And i get the following output:
```
×  test: Test (1 failed)
     ✔  File /root/test.json should be file
     ✔  Json /root/test.json ["hash", "subhash", "key"] should eq "value"
     ✔  Json /root/test.json ["array"] should include "zero"
     ×  Json /root/test.json ["array", 0] should eq "zero"

     expected: "zero"
          got: [nil, nil, nil]

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -"zero"
     +[nil, nil, nil]
```
Hash access and access to the array node itself is working as expected but indexed access to the array is not working, only returning nil objects.

### InSpec and Platform Version

inspec version 1.16.1

### PR DESCRIPTION
**Pull request by adamleff**
When attempting to access array values via the `json` resource:

```
describe json('/tmp/test.json') do
      its(['array',0]) { should eq "zero" }
end
```

... the resulting data would be an array of the size of the original array
with all the values replaced with nils:

```
     expected: "zero"
          got: [nil, nil, nil]
```

This was due to a bug in the ObjectTraverser mixin that mapped array values
back through `extract_value` rather than properly handling the passed-in
key(s). This worked fine for the specific data format created by the `csv`
resource but did not work `json` or any other resource that subclassed the
`JsonConfig` resource.

This change fixes the logic when dealing with an array when it's encountered,
and fixes up the `csv` resource with its own `value` method.

This change also adds tests for ObjectTraverser.

Fixes #1560

### CODE REVIEW

File: test/unit/resources/csv_test.rb [hunk 1]
```diff
@@ -17,19 +17,23 @@
...
+      _(resource.params.length).must_equal 4
     end
 
     it 'captures a hashmap of entries of a line' do
       _(resource.params[0]).must_be_kind_of Hash
     end
 
     it 'gets params by header fields' do
-      _(resource.params[0]['addressable']).must_equal 'ast'
+      _(resource.params[0]['name']).must_equal 'addressable'
```
Comment (chris-rock) [inline test/unit/resources/csv_test.rb:28]: man, who wrote this in the first place :-)

**Review by chris-rock — APPROVED** [review]
Thank you @adamleff

**Comment by chris-rock** [comment]
giphy 3
