### PR TITLE
Fix related to loading dependent profiles from a profile in shell

### LINKED ISSUE #3411: `inspec shell` does not work when `--depends`ing on profiles that themselves have dependencies
### 🎛 Description

🐛 bug report

`inspec shell` when used with `--depends=` on profile(s) that themselves have `depends` section defined in their `inspec.yml` file fail out with a stack trace. This complicates development of profiles that are composed of shared custom resources located in another folder.

### 🌍 InSpec and Platform Version

Confirmed in both…

`inspec` 2.2.102 / macOS 10.13.6
`ChefDK` 3.2.30-1 / `inspec` 2.2.70 / CentOS 7

### 🤔 Replication Case

Straightest path…

```bash
git clone https://github.com/inspec/inspec
cd inspec/examples/inheritance
inspec shell --depends=. # Fails with stack trace
inspec exec . # Works as expected
```

### 💁 Possible Solutions

Seemingly, the issue is that there a number of methods inside of `FileProvider` that expect a string but are receiving a symbol - I'm not sure if it's a symptom of something larger.

I intend to dig in further this evening to try to dig up more info, but wanted to get this filed in case someone had a eureka moment when reviewing it on how to get this fixed.

### 💻 Stacktrace

```
Traceback (most recent call last):
	23: from /usr/bin/inspec:292:in `<main>'
	22: from /usr/bin/inspec:292:in `load'
	21: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/bin/inspec:12:in `<top (required)>'
	20: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	19: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/cli.rb:225:in `shell_func'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/shell.rb:22:in `start'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/runner.rb:239:in `eval_with_virtual_profile'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/runner.rb:239:in `each'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:209:in `load_libraries'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:65:in `block in each'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/requirement.rb:124:in `profile'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:72:in `for_fetcher'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:56:in `for_path'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:53:in `relative_provider'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:53:in `new'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:190:in `initialize'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:231:in `get_prefix'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:245:in `get_folder_prefix'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:235:in `prefix_candidate_for': undefined method `end_with?' for :path:Symbol (NoMethodError)
```

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

Fix related to loading dependent profiles from a profile in shell
## Description

Fixes the issue of inspec shell which does not work when --depends is used for a profile that itself have dependencies 
## Related Issue

Fixes #3411 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/fetcher/local.rb [hunk 1]
```diff
@@ -3,7 +3,7 @@
 module Inspec::Fetcher
   class Local < Inspec.fetcher(1)
     name "local"
-    priority 0
+    priority 1
```
Comment (Vasu1105) [inline lib/inspec/fetcher/local.rb:6]: @Nik08 just in case if you can add some dev docs / code comments here explaining about what this priority setting does? That will be great.

**Review by Vasu1105 — COMMENTED** [review]
This LGTM. Thanks @Nik08 :)

File: lib/inspec/fetcher/local.rb (hunk 1 above)
Comment (Nik08) [reply lib/inspec/fetcher/local.rb:6]: @Vasu1105 I will add the comments in this file since priority is used in a lot of libraries and it means different for each case. So I will mention how this was important in comments.

**Review by clintoncwolfe — APPROVED** [review]
Thanks!
