### PR TITLE
CHEF-642 Fix for inspec exec fails with git fetcher if current directory does not have .git directory

### LINKED ISSUE #6064: inspec git and url fetcher require the $pwd to be a git repo - with inspec exec or inspec supermarket
In my plain-old homedir ...

```shell
 ~ inspec supermarket exec dev-sec/mysql-baseline -t mock://
Traceback (most recent call last):
	36: from /Users/alippold/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	35: from /Users/alippold/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	34: from /Users/alippold/.rvm/gems/ruby-2.7.2/bin/inspec:23:in `<main>'
	33: from /Users/alippold/.rvm/gems/ruby-2.7.2/bin/inspec:23:in `load'
	32: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-bin-5.14.0/bin/inspec:11:in `<top (required)>'
	31: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/base_cli.rb:35:in `start'
	30: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	29: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	28: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	27: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	26: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	25: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	24: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	23: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	22: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	21: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/bundles/inspec-supermarket/cli.rb:47:in `exec'
	20: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/bundles/inspec-supermarket/cli.rb:47:in `each'
	19: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/bundles/inspec-supermarket/cli.rb:47:in `block in exec'
	18: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/runner.rb:216:in `add_target'
	17: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/profile.rb:79:in `for_target'
	16: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/profile.rb:25:in `resolve_target'
	15: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/profile.rb:25:in `new'
	14: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/cached_fetcher.rb:11:in `initialize'
	13: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher.rb:7:in `resolve'
	12: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:13:in `resolve'
	11: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:13:in `each'
	10: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:15:in `block in resolve'
	 9: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/bundles/inspec-supermarket/target.rb:23:in `resolve'
	 8: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:86:in `resolve_next'
	 7: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher.rb:7:in `resolve'
	 6: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:13:in `resolve'
	 5: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:13:in `each'
	 4: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/plugin/v1/registry.rb:15:in `block in resolve'
	 3: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher/url.rb:22:in `resolve'
	 2: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher/url.rb:33:in `resolve_from_string'
	 1: from /Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher/url.rb:82:in `transform'
/Users/alippold/.rvm/gems/ruby-2.7.2/gems/inspec-core-5.14.0/lib/inspec/fetcher/url.rb:139:in `default_ref': Profile git dependency failed with default reference - https://github.com/dev-sec/mysql-baseline.git - error running 'git remote show https://github.com/dev-sec/mysql-baseline.git': fatal: not a git repository (or any of the parent directories): .git (Inspec::FetcherFailure)
```
but if I move to a directory that is a `git` repo
```shell
➜  inspec git:(main) pwd
/Users/alippold/github/mitre/inspec
➜  inspec git:(main) inspec supermarket exec dev-sec/mysql-baseline -t mock://
Resolving dependencies...
[2022-05-16T19:08:25-04:00] WARN: inspec gem not found, skipping detecting of system plugins
[2022-05-16T19:08:27-04:00] WARN: URL target https://github.com/dev-sec/mysql-baseline transformed to https://github.com/dev-sec/mysql-baseline/archive/master.tar.gz. Consider using the git fetcher
[2022-05-16T19:08:27-04:00] WARN: Could not find platform target_id.

Profile:   DevSec MySQL Baseline (mysql-baseline)
Version:   4.0.5
Target:    mock://
Target ID:

  ↺  mysql-conf-01: ensure the service is enabled and running
     ↺  The `service` resource is not supported on your OS yet.
  ×  mysql-conf-02: only one instance of mysql should run on a server
     ×  Command: `pgrep -x -c mysqld`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-conf-03: enable secure configurations for mysql (9 failed)
     ×  MySQL Config entry [mysqld] safe-user-create
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] old_passwords
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] user
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] secure-file-priv
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] local-infile
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] skip-symbolic-links
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] skip-show-database
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] skip-grant-tables
     undefined method `[]' for nil:NilClass
     ×  MySQL Config entry [mysqld] allow-suspicious-udfs
     undefined method `[]' for nil:NilClass
  ×  mysql-conf-03b: enable secure configurations for mysql
     ×  Control Source Code Error mysql-baseline-master/controls/mysql_conf.rb:92
     undefined method `split' for nil:NilClass
  ×  mysql-conf-04: ensure the mysql data path is owned by mysql user
     ×  File
     Resource `file` is not supported on platform mock/unknown.
  ×  mysql-conf-05: ensure data path is owned by mysql user
     ×  File /ibdata1
     Resource `file` is not supported on platform mock/unknown.
  ×  mysql-conf-06: ensure log file is owned by mysql user
     ×  File
     Resource `file` is not supported on platform mock/unknown.
  ×  mysql-conf-07: ensure the mysql config file is owned by user root, group mysql
     ×  File
     Resource `file` is not supported on platform mock/unknown.
  ↺  mysql-conf-08: ensure the mysql hardening config file is owned by user root, group mysql
     ↺  Skipped control due to only_if condition.
  ×  mysql-conf-09: the use of MYSQL_PWD is insecure and can exploit the password
     ×  Command: `env`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-01: use supported mysql version in production
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select version();'`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-02: use mysql version 5 or higher
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select substring_index(version(),".",1);'`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-03: test database must be deleted
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'show databases like "test";'`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-04: deactivate annonymous user names
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select count(*) from mysql.user where user="";'`
     Resource `command` is not supported on platform mock/unknown.
  ↺  mysql-db-05: default passwords must be changed
     ↺  Skipped control due to only_if condition.
  ↺  mysql-db-05b: default passwords must be changed
     ↺  Skipped control due to only_if condition.
  ×  mysql-db-06: the grant option must not be used
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select count(*) from mysql.user where grant_priv="y" and User!="root" and User!="debian-sys-maint";'`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-07: ensure no wildcards are used for hostnames
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select count(*) from mysql.user where host="%"'`
     Resource `command` is not supported on platform mock/unknown.
  ×  mysql-db-08: it must be ensured that superuser can login via localhost only
     ×  Command: `mysql -uroot -piloverandompasswordsbutthiswilldo -sN -e 'select count(*) from mysql.user where user="root" and host not in ("localhost","127.0.0.1","::1")'`
     Resource `command` is not supported on platform mock/unknown.


Profile Summary: 0 successful controls, 15 control failures, 4 controls skipped
Test Summary: 0 successful, 23 failures, 4 skipped
➜  inspec git:(main)
```

Related https://github.com/mitre/inspec-developer/issues/37

### PR DESCRIPTION
**Pull request by Vasu1105**
## Description

This fixes #6064 for git fetcher (inspec git fetcher requires the $pwd to be a git repo)
This PR includes a bug fix in the git fetcher

* Enables to fetch git profile irrespective of whether the current directory executing inspec has the .git or not.
* It clones the git profile and git checkout it to the default HEAD branch and does not require resolving reference
* Removes the logic from the git fetcher to get the default branch, it was using `git remote show` command that requires the current directory to be git repo and was causing the git fetch to fail in case the current directory does not have .git directory.
* Tested with a profile that has a dependent profile with a GIT URL.
* Tested with the relative path.
* Updated unit and functional test as per new changes.

Test covering the failure https://buildkite.com/chef-oss/inspec-inspec-inspec-5-verify/builds/16#018a265e-c1fd-49b5-9562-c2575be5ee8d/710-731 (surprisingly currently this is only failing on ruby 3.1) Note: this reference is from my earlier PR which I opened against the inspec-5 branch.

Passing Test after fix:
https://buildkite.com/chef/inspec-inspec-main-verify-private/builds/66
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/fetcher/git.rb [hunk 1]
```diff
@@ -205,14 +211,21 @@ def clone(dir = @repo_directory)
 
     def checkout(dir = @repo_directory)
       clone(dir)
-      git_cmd("checkout #{resolved_ref}", dir)
+      if resolved_ref.nil?
```
Comment (Nik08) [inline lib/inspec/fetcher/git.rb:216]: Maybe if we can add a comment on these conditions, it will be useful to determine the scenarios in future.

**Review by Nik08 — APPROVED** [review]
Great tests, looks good to me. We can maybe just add few more comments to remember the scenarios we just handled

**Review by clintoncwolfe — APPROVED** [review]
