### PR TITLE
windows_feature resource: Add DISM support

### LINKED ISSUE #3141: windows_feature resource fails on windows client OS types
### 🎛 Description

🐛 bug report

After installing a Windows feature on a client OS like Windows 10 the windows_feature resource in a test always fails due to the `Get-WindowsFeature` cmdlet not being available on client operating systems. 

https://github.com/inspec/inspec/blob/7b23fa479c516beaa0bd81d209ecf63133af2488/lib/resources/windows_feature.rb#L55  
Even if you install that module onto a client operating system you'll get this error:

`get-windowsfeature : The target of the specified cmdlet cannot be a Windows client-based operating system.`

### 🌍 InSpec and Platform Version

Running InSpec 1.51.21 on Windows 10

### 🤔 Replication Case

1. Install a new feature (e.g. `dism /online /enable-feature /all /featurename:telnetclient`) on Windows 10.
2. Run an InSpec test to test for the existence of this new feature like so
```
control 'telnet client enabled' do
  describe windows_feature('TelnetClient') do
    it { should be_installed }
  end
end
```
3. Test should fail

### 💁 Possible Solutions

My suggestion would be using DISM to check for the existence of the feature (e.g. `dism /online /get-featureinfo /featurename:TelnetClient`). DISM is a tool I know is installed on both client and server Windows operating systems. Also DISM will return 0 if the feature exists and something else if it doesn't which could help make the windows_feature resource a bit cleaner.

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This modifies the `windows_feature` resource to fallback to DISM when the `Get-WindowsFeature` command is not available.

This closes #3141

### CODE REVIEW

File: lib/resources/windows_feature.rb [hunk 1]
```diff
@@ -1,40 +1,24 @@
...
 
-# check for a Windows feature
-# Usage:
-# describe windows_feature('DHCP Server') do
-#   it{ should be_installed }
-# end
-#
-# deprecated serverspec syntax:
-# describe windows_feature('IIS-Webserver') do
-#   it{ should be_installed.by("dism") }
```
Comment (TheLunaticScripter) [inline lib/resources/windows_feature.rb:11]: So I don't think this can be done but it would be nice to have the option to select what command runs the check, ie dism powershell or something else. The main reasoning would be that the names of features are slightly different and it would be a better user story if the user can control that.

**Review by TheLunaticScripter — APPROVED** [review]

**Review by TheLunaticScripter — APPROVED** [review]

**Comment by jerryaldrichiii** [comment]
I agree @TheLunaticScripter, I pushed another commit up that adds this feature. Let me know what you think.

**Review by TheLunaticScripter — APPROVED** [review]
Awesome

**Review by jquick — COMMENTED** [review]
This looks pretty good to me. Confirm for me that we are not going to bust the legacy
```
it{ should be_installed.by("dism") }
```
 format. I dont see the support code for it but I want to make sure im not crazy.

**Comment by jerryaldrichiii** [comment]
@jquick Should be good, we never supported `.by`. Those examples were for ServerSpec.

**Comment by jquick** [comment]
ah missed the `deprecated serverspec syntax:` we should be good

**Review by jquick — APPROVED** [review]
Thanks @jerryaldrichiii

File: lib/resources/windows_feature.rb [hunk 2]
```diff
@@ -1,84 +1,126 @@
...
+      end
+    EOX
+
+    def initialize(feature, method = nil)
       @feature = feature
+      @method = method
       @cache = nil
 
       # verify that this resource is only supported on Windows
       return skip_resource 'The `windows_feature` resource is not supported on your OS.' if !inspec.os.windows?
```
Comment (miah) [inline lib/resources/windows_feature.rb]: I don't think we need this as we already have `supports platform: 'windows'` on line 6.

**Review by miah — APPROVED** [review]
This looks good apart from my one point about platform.

File: lib/resources/windows_feature.rb (hunk 2 above)
Comment (jerryaldrichiii) [reply lib/resources/windows_feature.rb]: Agreed! Bit out of scope but I'm always willing to clean up old code. Fixed in latest commit.
