### PR TITLE
Accept input keys via the Runner API

### LINKED ISSUE #237: Inputs are not passed to InSpec during kitchen verify
# Version:

1.1.0

# Environment:

Target machine is Ubuntu 18.04 with Chef 15 being installed
Machine running Test Kitchen is Windows 10

# Scenario:

I am trying to set inputs in the `kitchen.yml` file thus:

```yaml
    verifier:
      inspec_tests:
        - path: test/integration/camsa
      inputs:
        username: <%= ENV['CAMSA_USERNAME'] || 'foobar' %>
        managed_app: <%= ENV['MANAGED_APP'] || false %>
        automate_fqdn: <%= ENV['AUTOMATE_FQDN'] || 'tk-automate.managedautomate.io' %>
        customer_name: <%=
          firstname = ENV['CAMSA_FIRSTNAME'] || 'Foo'
          lastname = ENV['CAMSA_LASTNAME'] || 'Bar'
          '%s %s' % [firstname, lastname]
        %>   
```

However when the tests run they do not get these values.

When I run `kitchen diagnose --all` I can see that the verifier section has values, it appears that they are not respected by inspec.

```
verifier:
  chef_omnibus_root: "/opt/chef"
  command_prefix:
  debug:
  ftp_proxy:
  http_proxy:
  https_proxy:
  inputs:
    username: foobar
    managed_app: false
    automate_fqdn: tk-automate.managedautomate.io
    customer_name: Foo Bar
  inspec_tests:
  - path: test/integration/camsa
```

# Steps to Reproduce:

Set input values in Test Kitchen and run a test similar to the following

```ruby
customer_name = input('customer_name', value: '')

# Check that the license has been applied properly and registered with the correct user
cmd = 'curl https://127.0.0.1/api/v0/license/status -k --cert /hab/svc/deployment-service/data/deployment-service.crt --key /hab/svc/deployment-service/data/deployment-service.key --cacert /hab/svc/deployment-service/data/root.crt'
describe json({command: cmd}) do
  its ('customer_name') { should include customer_name }
end
```

# Expected Result:

The `customer_name` should be populated with "Foo Bar"

# Actual Result:

The output of this test shows that `customer_name` is still blank

```
  JSON from command: curl https://127.0.0.1/api/v0/license/status -k --cert /hab/svc/deployment-service/data/deployment-service.crt --key /hab/svc/deployment-service/data/deployment-service.key --cacert /hab/svc/deployment-service/data/root.crt
     [PASS]  customer_name should include ""
```

### LINKED ISSUE #3856: Rename Runner API inputs field
### 🎛 Description

As part of #3802, rename the runner API inputs field.

This is closely tied to https://github.com/inspec/kitchen-inspec/issues/224

Refs https://github.com/chef-cookbooks/audit/issues/360

### PR DESCRIPTION
**Pull request by clintoncwolfe**
## Description

As part of the Attribute to Input rename (#3802), this allows the Runner API to accept Input data under the keys `:inputs`, `:input_file`, or `input_files`. 

The Runner API is the set of arguments accepted by `Inspec::Runner.new`.  This is the path of execution used by both the audit-cookbook and kitchen-inspec.

Review notes: To test the Runner API, we need to spawn an InSpec process running from a library call, not from the CLI. The approach taken here was to generate a temporary script and execute that. There are other approaches, with other tradeoffs; I welcome thoughts.

## Related Issues

Closes #3856 
Fixes https://github.com/inspec/kitchen-inspec/issues/237
Refs #4290

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: test/functional/inputs_test.rb [hunk 1]
```diff
@@ -67,6 +68,88 @@
...
+    # options:
+    #   profile: path to profile to run
+    #   All other opts passed to InSpec::Runner.new(...)
+    # then add.target is called
+    def run_runner_api_process(options)
+      # Remove profile from options. All other are passed to Runner.
+      profile = options.delete(:profile)
+
+      # Make a tmpfile
+      Tempfile.open(mode: 0700) do |script| # 0700 - rwx
```
Comment (miah) [inline test/functional/inputs_test.rb]: If the intention is to show what that mode 0700 does, I'd comment with `-rwx------`

**Review by miah — APPROVED** [review]
Thanks @clintoncwolfe

File: test/functional/inputs_test.rb [hunk 2]
```diff
@@ -67,6 +68,88 @@
...
+        structured_output = JSON.parse(output)
+        assert_equal "passed", structured_output["profiles"][0]["controls"][0]["results"][0]["status"]
+      end
+    end
+
+    describe "when using the legacy :attributes key" do
+      let(:runner_options) { common_options.merge({ attributes: { test_input_01: "value_from_api" } }) }
+      it "finds the values but issues a DEPRECATION warning" do
+        output = run_result.stdout
+        assert_includes output, "DEPRECATION"
```
Comment (miah) [inline test/functional/inputs_test.rb:138]: This isn't working on windows, possibly as noted on line 125. 

https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/335#07b2c79d-fa5b-4ef9-9b5e-55693f85657f/586-607

Do we have a issue, or plan for fixing this? Maybe skipping the test when run on windows until the issue is resolved?

File: test/functional/inputs_test.rb [hunk 3]
```diff
@@ -67,6 +68,88 @@
...
+      end
+    end
+
+    describe "when using the current :inputs key" do
+      let(:runner_options) { common_options.merge({ inputs: { test_input_01: "value_from_api" } }) }
+
+      it "finds the values and does not issue any warnings" do
+        output = run_result.stdout
+        refute_includes output, "DEPRECATION"
+        structured_output = JSON.parse(output)
```
Comment (miah) [inline test/functional/inputs_test.rb:128]: Maybe also related to the comment on 125. This one isn't working on windows either. Maybe this one also needs a skip on windows until the compatibility issue is resolved?

https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/335#07b2c79d-fa5b-4ef9-9b5e-55693f85657f/586-611

**Review by miah — CHANGES_REQUESTED** [review]

**Review by miah — APPROVED** [review]
Ok Lets go! 🐱‍👤

File: Rakefile [hunk 4]
```diff
@@ -80,7 +80,7 @@ namespace :test do
     missing.reject! { |f| ! File.file? f }
     missing.reject! { |f| f =~ %r{test/(integration|cookbooks)} }
     missing.reject! { |f| f =~ %r{test/unit/mock} }
-    missing.reject! { |f| f =~ %r{test.*helper} }
+    missing.reject! { |f| f =~ /test.*helper/ }
```
Comment (zenspider) [inline Rakefile:83]: Yeah... why is this commit even needed? master should be fully compliant so what happened?

File: test/functional/inputs_test.rb [hunk 5]
```diff
@@ -67,6 +68,88 @@
...
+        # inject target
+        script.puts %q{ # Profile to run: }
+        script.puts " profile_location = \"#{profile}\""
+        script.puts
+
+        # create runner with opts
+        script.puts %q{ # Run Execution }
+        script.puts %q{ runner = Inspec::Runner.new(runner_args) }
+        script.puts %q{ runner.add_target profile_location }
+        script.puts %q{ runner.run }
```
Comment (zenspider) [inline test/functional/inputs_test.rb]: This would read nicer and be easier to maintain as one puts w/ a heredoc

File: test/unit/mock/profiles/inputs/via-runner/inspec.yml [hunk 6]
```diff
@@ -0,0 +1,6 @@
+name: via-runner
+license: Apache-2.0
+summary: Profile to test inspec loading inputs via the Runner API (audit cookbook / kitchen inspec)
+version: 0.1.0
+supports:
+  platform: os
```
Comment (zenspider) [inline test/unit/mock/profiles/inputs/via-runner/inspec.yml]: EOF should have EOL

File: lib/inspec/input_registry.rb [hunk 7]
```diff
@@ -152,7 +152,7 @@ def bind_inputs_from_runner_api(profile_name, input_hash)
           file: loc.path,
           line: loc.lineno
         )
-        find_or_register_input(input_name, profile_name, event: evt)
+        find_or_register_input(input_name.to_s, profile_name, event: evt)
```
Comment (zenspider) [inline lib/inspec/input_registry.rb]: Why is this necessary? We seem to have a ton of `to_sym` and `to_s` littered all over the code and I can't tell if it is cargo-culting, or our lack of hygiene, or something else. Shouldn't this be the responsibility of `find_or_register_input` to accept a wide(r) range of inputs but deal with them correctly?

**Review by zenspider — CHANGES_REQUESTED** [review]
Oops. I thought I submitted this yesterday.

Some confusion and minor requests.

File: Rakefile (hunk 4 above)
Comment (clintoncwolfe) [reply Rakefile:83]: This was chefstyle -a being applied.  I imagine in this case it felt the %r was not needed because there are no path separators.... 

and yes, I just checked, it does change it back to that, //.

File: lib/inspec/input_registry.rb (hunk 7 above)
Comment (clintoncwolfe) [reply lib/inspec/input_registry.rb]: Sure, I'll happily move the call within the find_or_register_input method.

File: test/functional/inputs_test.rb (hunk 5 above)
Comment (clintoncwolfe) [reply test/functional/inputs_test.rb]: Okay

File: test/functional/inputs_test.rb [hunk 8]
```diff
@@ -86,44 +86,34 @@ def run_runner_api_process(options)
...
+          runner.add_target profile_location
+          runner.run
+        EOSCRIPT
         script.flush
 
         train_cxn = Train.create("local", command_runner: :generic).connection
         # TODO - portability - this does not have windows compat stuff from the inspec() method in functional/helper.rb
         # it is not portable to windows at this point yet.
-        train_cxn.run_command("ruby #{script.path}") # TODO get path to file
+        train_cxn.run_command("ruby #{script.path}")
```
Comment (zenspider) [inline test/functional/inputs_test.rb]: Couldn't this use `CMD` instead of `train_cxn` ? And the `inspec` call (or friends).

File: Rakefile (hunk 4 above)
Comment (zenspider) [reply Rakefile:83]: What I was asking is how this PR needed this at all? Master should be clean wrt chefstyle, so how did this come about?

**Comment by zenspider** [comment]
This is failing tests right now. More string vs symbol stuff.

At some point, I'm gonna want us to unify and get over this confusion. We're doing it wrong:

```
10029 % ag \\.to_s -w --ruby -c lib test | cut -f 2 -d: | add
sum   =   285.000                                      2.397
count =   126
mean  =     2.262
sd    =     2.397
10030 % ag \\.to_sym -w --ruby -c lib test | cut -f 2 -d: | add
sum   =    84.000                                      1.718
count =    43
mean  =     1.953
sd    =     1.718
```

File: test/functional/inputs_test.rb (hunk 8 above)
Comment (clintoncwolfe) [reply test/functional/inputs_test.rb]: It could use CMD, that's not an issue. 

`inspec` and friends set the executable, though (by injecting `exec_inspec`)- here we need it to be `ruby`.

Comment (clintoncwolfe) [reply test/functional/inputs_test.rb]: opened #4416 to track

**Comment by clintoncwolfe** [comment]
Well, the string vs symbol stuff is due to the input names now always being stored as strings - due to the requested change on ada6aad to move the .to_s inside the body of find_or_register_input(). The unit test had some mocks that were expecting symbols, just needed to update them - I should have caught that and made that change on ada6aad.

I totally agree, though, that we have a lot of confusion on our hands in general regarding strings vs symbols, and a lot of potential for trouble.

**Review by zenspider — APPROVED** [review]
thank you for filing the extra issue to track
