### PR TITLE
Use target helpers in Inspec::Profile#from_file

### LINKED ISSUE #408: InSpec check crashes on tarball
```
inspec check profile.tar.gz 
/Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:30:in `initialize': Cannot find directory profile.tar.gz (RuntimeError)
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:15:in `new'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:15:in `from_path'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:151:in `check'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:228:in `<top (required)>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `load'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `<main>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

### PR DESCRIPTION
**Pull request by srenatus**
Before: Inspec::Profile was expecting a profile in a filesystem.
After: Inspec::Profile operates on the contents as returned from the target helper 

Fixes #408.

### CODE REVIEW

**Comment by srenatus** [comment]
Phew, so travis-ci has `tar` and `zip`.

File: lib/inspec/profile.rb [hunk 1]
```diff
@@ -19,29 +19,27 @@ def self.from_path(path, options = nil)
...
-      @runner.add_tests([@path], @options)
+
+      @options[:ignore_supports] = true
+      tests, libs, metadata = @runner.add_tests([@path], @options)
+      @content = tests + libs + metadata
+
+      # NB if you want to check more than one profile, use one
+      # Inspec::Profile#from_file per profile
+      m = metadata.first
+      @metadata = Metadata.from_ref(m[:ref], m[:content], @profile_id, @logger)
```
Comment (arlimus) [inline lib/inspec/profile.rb:43]: imho parse metadata beore adding/parsing tests; if anything fails with metadata, we don't jump into parsing tests

**Comment by chris-rock** [comment]
Thanks @renatus for this great fix

**Comment by srenatus** [comment]
Wait... that order... is... important? :grey_question:  :confused: :grey_question:

Thanks for catching that @chris-rock :)

**Comment by chris-rock** [comment]
Needed this for #409 :-)
