### PR TITLE
Yum resource fix for non-existent repos and repo info

### LINKED ISSUE #1553: yum.repo with should_not exist fails with NoMethodError: undefined method `[]' for nil:NilClass
### Description

While converting a cookbook from Serverspec to Inspec I found testing for a yum repo using `yum.repo` that does not exist causes Inspec to break.

### InSpec and Platform Version

1.11.0 (ChefDK 1.2.22)

### Replication Case

Using the original resource from my serverspec test:

File:

```
describe yumrepo('internal') do
  it { should exist }
  it { should be_enabled }
end

describe yumrepo('epel') do
  it { should_not exist }
end
```

Output:

```
[DEPRECATION] `yumrepo(reponame)` is deprecated.  Please use `yum.repo(reponame)` instead.
[DEPRECATION] `yumrepo(reponame)` is deprecated.  Please use `yum.repo(reponame)` instead.
[DEPRECATION] `yumrepo(reponame)` is deprecated.  Please use `yum.repo(reponame)` instead.

Target:  docker://6f0853576e7fe411561c21959ea58963057ae63da3a7b539bda877bba8bd8933


  Yum Repository
     ✔  should exist
     ✔  should be enabled
  Yum Repository
     ✔  should not exist

Test Summary: 3 successful, 0 failures, 0 skipped
```

Using the new `yum.repo('name')` format.

File:

```
describe yum.repo('internal') do
  it { should exist }
  it { should be_enabled }
end

describe yum.repo('epel') do
  it { should_not exist }
end
```

Output:

```
[root@localhost /]# inspec exec test.rb
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/resources/yum.rb:139:in `to_s': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/metadata.rb:180:in `build_description_from'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/metadata.rb:133:in `populate'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/metadata.rb:258:in `create'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:420:in `set_it_up'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:384:in `subclass'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner_rspec.rb:27:in `example_group'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:238:in `get_check_example'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:264:in `block in register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:263:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:263:in `flat_map'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:263:in `register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:94:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:93:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:93:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/runner.rb:100:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/base_cli.rb:82:in `run_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/inspec/cli.rb:158:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:22:in `load'
        from /usr/bin/inspec:22:in `<main>'
```

Confirmed using the shell:

```
inspec> describe yumrepo('epel') do
inspec>   it { should_not exist }
inspec> end
[DEPRECATION] `yumrepo(reponame)` is deprecated.  Please use `yum.repo(reponame)` instead.

Profile: inspec-shell
Version: (not specified)

  Yum Repository
     ✔  should not exist

Test Summary: 1 successful, 0 failures, 0 skipped

inspec> describe yum.repo('epel') do
inspec>   it { should_not exist }
inspec> end
after_eval hook failed: NoMethodError: undefined method `[]' for nil:NilClass
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.16.1/lib/resources/yum.rb:139:in `to_s'
(see _pry_.hooks.errors to debug)
```

### PR DESCRIPTION
**Pull request by adamleff**
If a repo did not exist, running matchers against it (such as `exist`)
were failing due to a bug in `#to_s` when fetching the repo name. The
`info` method would return nil and we'd still try to treat it as a hash.

This change ensures that info is always a hash, possibly empty if the
repo doesn't exist, and uses the repo name provided by the user rather
than shortening it to be consistent with our other resources which don't
manipulate the user input in the formatter.

Also added a method_missing to allow users to interrogate repo options,
such as baseurl or gpgcheck.

Fixes #1553

### CODE REVIEW

File: lib/resources/yum.rb [hunk 1]
```diff
@@ -33,7 +32,7 @@
 module Inspec::Resources
   class Yum < Inspec.resource(1)
     name 'yum'
-    desc 'Use the yum InSpec audit resource to test packages in the Yum repository.'
+    desc 'Use the yum InSpec audit resource to the configuration of Yum repositories.'
```
Comment (shoekstra) [inline lib/resources/yum.rb]: This is missing the word "test" and should be:

```desc 'Use the yum InSpec audit resource to test the configuration of Yum repositories.'```

Sorry for being pedantic :)

Comment (adamleff) [reply lib/resources/yum.rb]: Pedants welcome. I'm the club president.

File: lib/resources/yum.rb [hunk 2]
```diff
@@ -121,22 +120,25 @@ def shortname(id)
...
     end
 
     def enabled?
-      repo = info
-      return false if repo.nil?
+      return false unless exist?
       info['status'] == 'enabled'
     end
 
+    def method_missing(name)
```
Comment (chris-rock) [inline lib/resources/yum.rb]: We try to avoid method_missing whenever possible. Do we know all possible properties? Maybe we use something like:

```
    %w{
      baseurl
    }.each do |m|
      define_method m.to_sym do |*args|
        info[m.to_s]
      end
    end
```

File: lib/resources/yum.rb [hunk 3]
```diff
@@ -22,6 +20,7 @@
 # describe yum.repo('epel') do
 #   it { should exist }
 #   it { should be_enabled }
+#   its('baseurl') { should include 'mycompany.biz' }
```
Comment (chris-rock) [inline lib/resources/yum.rb:23]: should this be `baseurl` or ruby style `base_url`?

File: lib/resources/yum.rb [hunk 4]
```diff
@@ -121,22 +120,25 @@ def shortname(id)
...
       info['status'] == 'enabled'
     end
 
+    def method_missing(name)
+      info[name.to_s]
+    end
+
     def to_s
-      "YumRepo #{shortname(info['id'])}"
+      "YumRepo #{@reponame}"
```
Comment (chris-rock) [inline lib/resources/yum.rb:153]: Thank you 👍

File: lib/resources/yum.rb (hunk 3 above)
Comment (adamleff) [reply lib/resources/yum.rb:23]: The key in the yum output and in the `*.repo` files is `baseurl` so I vote for keeping it consistent.

File: lib/resources/yum.rb [hunk 5]
```diff
@@ -121,22 +120,37 @@ def shortname(id)
...
 
     def exist?
-      !info.nil?
+      !info.empty?
     end
 
     def enabled?
-      repo = info
-      return false if repo.nil?
+      return false unless exist?
```
Comment (arlimus) [inline lib/resources/yum.rb:132]: Nice simplification

**Review by arlimus — APPROVED** [review]
Great update and more usefull methods here, kudos @adamleff
