### PR TITLE
Fix mysql_session resource to raise exception if there is a error in connection or in query

### LINKED ISSUE #5309: SQL session resources should throw an error or warning if you try to execute a query but there is no valid session established
At the moment - if for some reason the sql session of the database resources do not make it clear that you are trying to query a nil sql session and it is cauing invalid results.

We should add some logic in the session and the query resources to protect aginst this case.

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

Fix mysql_session resource to handle the exceptions if the mysql session is not established. Currently it does not raise any exception due to which the InSpec test gives false result
## Related Issue

Fixes #5309 for mysql_session resource.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/resources/mysql_session.rb [hunk 1]
```diff
@@ -68,6 +72,12 @@ def to_s
 
     private
 
+    # Querying on the database to make sure conneciton can be established. If not this will set the resource exception
+    # message which we raise before querying on the database using mysql_session object.
+    def set_connection
```
Comment (clintoncwolfe) [inline lib/inspec/resources/mysql_session.rb]: I suggest we rename this to be "test connection" and use a query like "SELECT 1" - some users might not have permission to list databases.

**Review by clintoncwolfe — APPROVED** [review]
Looks good, waiting to merge until after tomorrow's release!
