### PR TITLE
use multipart gem for upload to support upload on windows

### LINKED ISSUE #3245: inspec compliance upload - upload error
### 🎛 Description

🐛 bug report

Hi 

I'm attempting to upload a profile to my A2 server.  I've been able to logon to a2 through inspec and can query profiles etc.  Yet it seems to error at the uploading stage.  The error reports that I should run inspec check but I know my profile is good, inspec check passes and using the gui I can upload the file that inspec created and it uploads fine.

### 🌍 InSpec and Platform Version

2.2.42 on windows 10

### 🤔 Replication Case

```
 bundle exec ruby .\bin\inspec compliance upload C:\git-repo\niu\microsoft-windows-server
Profile is already vendored. Use --overwrite.
I, [2018-07-23T14:05:23.429696 #20836]  INFO -- : Checking profile in C:\DevOps\git-repo\niu\microsoft-windows-server
I, [2018-07-23T14:05:23.430697 #20836]  INFO -- : Metadata OK.
I, [2018-07-23T14:05:23.497744 #20836]  INFO -- : Found 6 controls.
I, [2018-07-23T14:05:23.497744 #20836]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz
I, [2018-07-23T14:05:23.789103 #20836]  INFO -- : Generate archive C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz.
I, [2018-07-23T14:05:23.800126 #20836]  INFO -- : Finished archive generation.
Start upload to admin/microsoft-windows-server
Uploading to Chef Automate
Error during profile upload:
rpc error: code = InvalidArgument desc = Check InSpec check failed for /hab/svc/compliance-service/data/profiles/.tmp/inspec-upload727119151.tar.gz with message: exit status 1
/hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `read': unexpected end of file (Zlib::GzipFile::Error)
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `from'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:59:in `each'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:140:in `find_all'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:140:in `block in initialize'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:160:in `walk_tar'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:139:in `initialize'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:14:in `new'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:14:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:55:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:72:in `for_fetcher'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:78:in `for_target'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/cli.rb:75:in `check'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/bin/inspec:12:in `<main>'
```

### 💁 Possible Solutions

If I use the file that was created ``` C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz ``` and logon to the gui I can upload the profile fine

### PR DESCRIPTION
**Pull request by chris-rock**
Fixes https://github.com/inspec/inspec/issues/3245

Signed-off-by: Christoph Hartmann <chris@lollyrock.com>

### CODE REVIEW

File: lib/bundles/inspec-compliance/http.rb [hunk 1]
```diff
@@ -60,7 +61,7 @@ def self.post_file(url, headers, file_path, insecure)
 
       req.body_stream=File.open(file_path, 'rb')
       req.add_field('Content-Length', File.size(file_path))
-      req.add_field('Content-Type', 'application/x-gtar')
+      req.add_field('Content-Type', 'application/gzip')
```
Comment (chris-rock) [inline lib/bundles/inspec-compliance/http.rb]: I am updating this to use x-gzip

**Review by jquick — APPROVED** [review]
Nice improvement! Thanks for this @chris-rock

**Review by clintoncwolfe — APPROVED** [review]
Refs #3373.  I wish this had tests; changes seem reasonable.
