### PR TITLE
CFINSPEC-252: Fix profile gem dependency installation is failing when  gem version is not specified

### LINKED ISSUE #6053: requried_gems seems to fail when a `version` is not provided
When using the new required gems capability in the `inspec.yml`, the `version` property seems to be expected.

I would have expected if a version was not given, that the lastest version would be installed.

If we are going to require both, then we should document clearly that both are _required_ for things to work and this should be added to the `inspec check` capability.

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

* Profile gem dependency installation works now if the gem version is not specified in the inspec.yml
* Updated the User prompt text for the profile gem dependency installation to be self-explanatory.
## Related Issue

Fixes #6053
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/inspec/profile.rb [hunk 1]
```diff
@@ -410,7 +410,7 @@ def load_gem_dependencies
           else
             ui = Inspec::UI.new
             gem_dependencies.each { |gem_dependency| ui.list_item("#{gem_dependency[:name]} #{gem_dependency[:version]}") }
-            choice = ui.prompt.select("Would you like to install profile gem dependencies listed above?", %w{Yes No})
+            choice = ui.prompt.select("The above listed gem dependencies are required to run profile. Would you like to install them ?", %w{Yes No})
```
Comment (clintoncwolfe) [inline lib/inspec/profile.rb]: "to run the profile"
