### PR TITLE
Fix --tags filter for dependent profiles

### LINKED ISSUE #5653: --tags does not support dependent profiles
### 🎛 Description

Like #5647, but for --tags.

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

## Description

- Fix `--tags` filter for dependent profiles, it was not able to filter dependent profiles till now.
- Introduced filtering logic for both `include_controls` and `require_controls` cases.
- Tested manually till 4 levels, A->B->C->D
## Related Issue

Fixes #5653 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by aaronlippold** [comment]
Some good testing content is here:

https://saf.cms.gov/#/validate

this one is three levels of chain:

https://github.com/CMSgov/cms-ars-3.1-moderate-aws-rds-oracle-database-12c-stig-overlay

**Comment by aaronlippold** [comment]
I woiuld suggest the unit test to do at least 4 to 5 levels of dep chain:

CORE -> ORG -> CLOUD -> TEAM -> REGION 

Is now a common pattern

**Comment by aaronlippold** [comment]
Where region could be east or west, or secure and non-secure data enviroments etc

File: lib/inspec/dsl.rb [hunk 1]
```diff
@@ -93,22 +93,29 @@ def self.load_spec_files_for_profile(bind_context, opts, &block)
...
     context.load(block) if block_given?
     bind_context.add_subcontext(context)
   end
 
-  def self.filter_included_controls(context, profile, &block)
+  def self.filter_included_controls(context, profile, opts, &block)
     mock = Inspec::Backend.create(Inspec::Config.mock)
     include_ctx = Inspec::ProfileContext.for_profile(profile, mock)
     include_ctx.load(block) if block_given?
+    include_ctx.control_eval_context.instance_variable_set(:@conf, opts[:conf])
```
Comment (clintoncwolfe) [inline lib/inspec/dsl.rb]: I had the same complaint on #5656 - we really should avoid instance_variable_Set on our own code whereever possible. we can make `conf` an attr_accessor on ControlEvalContext and set it properly.

Comment (Nik08) [reply lib/inspec/dsl.rb]: I understand now why you are suggesting to avoid using this. It goes against maintaining the class level encapsulations. Thanks for pointing this out. Have replaced this with `attr_accessor` usage.

**Comment by aaronlippold** [comment]
Does it also makes sense, while we are in this part of the codebase, to also round out the #5327 PR?

Perhaps we could just update the waived implemenation to auto-tag the control waived and then the --tags filter could take care of it? 

Read waived file, make hash, on the load_control add a `if in tagged, add 'wavied' tag to control`, on the internal run logic, `unless tagged hash empty, apend --skip-tagged=waived` 

This would also give us `--skip-contorols` and --skip-tagged` which could be very useful in the general case. These should be just the inverser logic of their counterparts.

So the argument could also be just to use `--skip-control` internally to do waivers.

In my openion, waived is just a special case of tagging.

**Comment by aaronlippold** [comment]
any blockers on this?

**Review by clintoncwolfe — APPROVED** [review]
Thanks!

**Comment by clintoncwolfe** [comment]
We'll keep #5327 separate for now - it's a lot more complex.
