### PR TITLE
Generate default profile names, fix bug when using multiple flat profiles

### LINKED ISSUE #1456: After inspec update from 1.5 to 1.10 it breaks with [undefined method `[]=' for nil:NilClass]
### Description

inspec breaks with `undefined method []=' for nil:NilClass` after the update inspec 1.5.0 -> 1.10.0

### InSpec and Platform Version

- inspec 1.10
- kitchen-inspec 0.17.0

### Replication Case

I could not easily replicate the problem, but it looks like there is a relation to the multiple test sets in the `.kitchen.yml`:

```yaml
  - name: role-ci-runner
    run_list:
      - recipe[test]
      - role[ci-runner]
    verifier:
      inspec_tests:
        - path-to-the-tests-1
        - path-to-the-tests-2
```

If I leave only one path there -> it works

**UPDATE:** replication case is here: https://github.com/artem-sidorenko/inspec-test

### Stacktrace

```
I, [2017-02-03T18:09:51.072073 #27384]  INFO -- Kitchen: -----> Starting Kitchen (v1.15.0)
I, [2017-02-03T18:09:53.858032 #27384]  INFO -- Kitchen: -----> Verifying <role-ci-runner-centos-7>...
E, [2017-02-03T18:09:58.527203 #27384] ERROR -- Kitchen: ------Exception-------
E, [2017-02-03T18:09:58.527306 #27384] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-02-03T18:09:58.527331 #27384] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `[]=' for nil:NilClass] on role-ci-runner-centos-7
E, [2017-02-03T18:09:58.527353 #27384] ERROR -- Kitchen: ----------------------
E, [2017-02-03T18:09:58.527374 #27384] ERROR -- Kitchen: ------Backtrace-------
E, [2017-02-03T18:09:58.527434 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-02-03T18:09:58.527474 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-02-03T18:09:58.527508 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-02-03T18:09:58.527542 #27384] ERROR -- Kitchen: /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-02-03T18:09:58.527577 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-02-03T18:09:58.527613 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-02-03T18:09:58.527649 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-02-03T18:09:58.527687 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
E, [2017-02-03T18:09:58.527725 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-02-03T18:09:58.527760 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-02-03T18:09:58.527793 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
E, [2017-02-03T18:09:58.527824 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
E, [2017-02-03T18:09:58.527856 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-02-03T18:09:58.527904 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-02-03T18:09:58.527935 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/bin/kitchen:13:in `<top (required)>'
E, [2017-02-03T18:09:58.527968 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/bin/kitchen:22:in `load'
E, [2017-02-03T18:09:58.528001 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/bin/kitchen:22:in `<main>'
E, [2017-02-03T18:09:58.528034 #27384] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-02-03T18:09:58.528065 #27384] ERROR -- Kitchen: -Composite Exception--
E, [2017-02-03T18:09:58.528095 #27384] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-02-03T18:09:58.528127 #27384] ERROR -- Kitchen: Message: Failed to complete #verify action: [undefined method `[]=' for nil:NilClass] on role-ci-runner-centos-7
E, [2017-02-03T18:09:58.528163 #27384] ERROR -- Kitchen: ----------------------
E, [2017-02-03T18:09:58.528200 #27384] ERROR -- Kitchen: ------Backtrace-------
E, [2017-02-03T18:09:58.528236 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:633:in `add_example'
E, [2017-02-03T18:09:58.528272 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:363:in `create_or_find_control'
E, [2017-02-03T18:09:58.528320 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:287:in `format_example'
E, [2017-02-03T18:09:58.528360 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:53:in `block in stop'
E, [2017-02-03T18:09:58.528397 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:52:in `map'
E, [2017-02-03T18:09:58.528436 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:52:in `stop'
E, [2017-02-03T18:09:58.528477 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:114:in `stop'
E, [2017-02-03T18:09:58.528513 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:201:in `block in notify'
E, [2017-02-03T18:09:58.528550 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `each'
E, [2017-02-03T18:09:58.528586 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `notify'
E, [2017-02-03T18:09:58.528622 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:195:in `stop'
E, [2017-02-03T18:09:58.528659 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:169:in `block in finish'
E, [2017-02-03T18:09:58.528696 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:187:in `close_after'
E, [2017-02-03T18:09:58.528733 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:168:in `finish'
E, [2017-02-03T18:09:58.528771 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:79:in `report'
E, [2017-02-03T18:09:58.528840 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
E, [2017-02-03T18:09:58.528875 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner_rspec.rb:77:in `run'
E, [2017-02-03T18:09:58.528907 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner.rb:117:in `run_tests'
E, [2017-02-03T18:09:58.528939 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner.rb:101:in `run'
E, [2017-02-03T18:09:58.528971 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:94:in `call'
E, [2017-02-03T18:09:58.529003 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-02-03T18:09:58.529036 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-02-03T18:09:58.529071 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-02-03T18:09:58.529107 #27384] ERROR -- Kitchen: /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-02-03T18:09:58.529142 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-02-03T18:09:58.529176 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-02-03T18:09:58.529213 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-02-03T18:09:58.529264 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-02-03T18:09:58.529303 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-02-03T18:09:58.529340 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-02-03T18:09:58.529379 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-02-03T18:09:58.529416 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-02-03T18:09:58.529453 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-02-03T18:09:58.529519 #27384] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-02-03T18:09:58.529555 #27384] ERROR -- Kitchen: ---Nested Exception---
E, [2017-02-03T18:09:58.529591 #27384] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-02-03T18:09:58.529624 #27384] ERROR -- Kitchen: Message: Failed to complete #verify action: [undefined method `[]=' for nil:NilClass]
E, [2017-02-03T18:09:58.529658 #27384] ERROR -- Kitchen: ----------------------
E, [2017-02-03T18:09:58.529691 #27384] ERROR -- Kitchen: ------Backtrace-------
E, [2017-02-03T18:09:58.529727 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:633:in `add_example'
E, [2017-02-03T18:09:58.529761 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:363:in `create_or_find_control'
E, [2017-02-03T18:09:58.529797 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:287:in `format_example'
E, [2017-02-03T18:09:58.529835 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:53:in `block in stop'
E, [2017-02-03T18:09:58.529872 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:52:in `map'
E, [2017-02-03T18:09:58.529912 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:52:in `stop'
E, [2017-02-03T18:09:58.529949 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/rspec_json_formatter.rb:114:in `stop'
E, [2017-02-03T18:09:58.529986 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:201:in `block in notify'
E, [2017-02-03T18:09:58.530025 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `each'
E, [2017-02-03T18:09:58.530064 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `notify'
E, [2017-02-03T18:09:58.530102 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:195:in `stop'
E, [2017-02-03T18:09:58.530137 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:169:in `block in finish'
E, [2017-02-03T18:09:58.530182 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:187:in `close_after'
E, [2017-02-03T18:09:58.530219 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:168:in `finish'
E, [2017-02-03T18:09:58.530258 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:79:in `report'
E, [2017-02-03T18:09:58.530306 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
E, [2017-02-03T18:09:58.530342 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner_rspec.rb:77:in `run'
E, [2017-02-03T18:09:58.530375 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner.rb:117:in `run_tests'
E, [2017-02-03T18:09:58.530409 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/inspec-1.10.0/lib/inspec/runner.rb:101:in `run'
E, [2017-02-03T18:09:58.530475 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:94:in `call'
E, [2017-02-03T18:09:58.530510 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-02-03T18:09:58.530546 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-02-03T18:09:58.530579 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-02-03T18:09:58.530614 #27384] ERROR -- Kitchen: /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-02-03T18:09:58.530651 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-02-03T18:09:58.530689 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-02-03T18:09:58.530726 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-02-03T18:09:58.530762 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-02-03T18:09:58.530799 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-02-03T18:09:58.530837 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-02-03T18:09:58.530875 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-02-03T18:09:58.530911 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-02-03T18:09:58.530947 #27384] ERROR -- Kitchen: /home/artem/.rvm/gems/ruby-2.3.3@chef/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-02-03T18:09:58.530984 #27384] ERROR -- Kitchen: ----End Backtrace-----
```

### PR DESCRIPTION
**Pull request by adamleff**
When running InSpec with multiple profiles, and two or more of the profiles
are read in using the "Flat" SourceReader (i.e. they are not actual profiles
with a metadata file like inspec.yml, but rather just a folder containing
.rb files with controls and tests in them), InSpec would throw a NilClass
error when building the necessary objects for the formatter.

broken

The cause was in `#profile_contains_example` in the formatter code which
checks to see if the profile name is the same as the profile_id in the given
example. However, if both of those were nil, it would potentially match the
wrong Flat-read profile. By refusing to match if either are nil, we fix the
syntax issue, but the output is confusing:

fixed but confusing

The tests now run and are outputted, but we erroneously show targets that have no tests run, and the tests from the two profiles are jumbled together. By assigning a default name to a profile that has no title/name, we can clean up the output and provide our user more helpful information about their tests.

fixed

Fixes #1456.

Signed-off-by: Adam Leff <adam@leff.co>

### CODE REVIEW

File: lib/inspec/metadata.rb [hunk 1]
```diff
@@ -177,27 +177,45 @@ def self.finalize_supports(supports, logger)
...
+      unless profile_id.to_s.empty?
+        metadata.params[:name] = profile_id.to_s
+        return
+      end
+
+      # don't overwrite an existing name
+      return unless metadata.params[:name].nil?
+
+      # if there's a title, there is no need to set a name too
+      return unless metadata.params[:title].nil?
```
Comment (chris-rock) [inline lib/inspec/metadata.rb:191]: I am not sure if we should allow to set the name by `title`. This may be confusing. Do we have any additional value by supporting that? If the `inspec.yml` is available, but `name` is not specified, we could also display `(not specified)`

**Review by chris-rock — COMMENTED** [review]
Thank you for the fix and the improved test coverage. I am not sure we should support a fallback to `title`.

File: lib/inspec/metadata.rb (hunk 1 above)
Comment (adamleff) [reply lib/inspec/metadata.rb:191]: I'm confused by this comment. We don't actually set the name by `title`. This simply does not set a default `name` if there's already a `title` field because it would be counter-intuitive to our users.

Example, if I had a profile inspec.yml with `title: My Profile`, without this line, we would leave the title alone AND create a `name` containing "tests from tests/foo"... and then you'd have CLI formatter output looking like this:

```
Profile: My Profile (tests from tests/foo)
```

... which might be fine but felt like added functionality out of the scope of this bug fix. Therefore, I opted not to add a `name` if there was already a `title`.

Comment (chris-rock) [reply lib/inspec/metadata.rb:191]: Agreed, makes sense to me

**Review by chris-rock — APPROVED** [review]
Great improvement @adamleff
