### PR TITLE
Try to decode archive contents to UTF-8 to avoid encoding corruption.

### LINKED ISSUE #4135: Encoding issue with JSON reporter + .tar.gz profiles
InSpec 4.3.2 from rubygems

This looks very similar to https://github.com/inspec/inspec/issues/3815 but
a. only affects tar'red profiles
b. Is due to non-ASCII chars in the profile itself and not in bad chars returned from the target host.

This is also very similar to https://github.com/inspec/inspec/issues/2938 but that issue affected all execution (not just when using JSON output) and also that issue was tested as fixed at the time.

This was originally raised as https://github.com/dev-sec/nginx-baseline/issues/33 but that was closed with a workaround.

**To reproduce:**
 * init a new profile
 * Edit `controls/example.rb` to be:

```
title 'My cool controls'

control 'control-01' do
  impact 1.0
  title 'Cool title'
  desc 'Check out my “cool” quote characters.'
  describe 'a' do
    it { should eq 'a' }
  end
end
```

Note the non-ASCII quote characters in the `desc`.

* Archive the profile
* Attempt to either exec the profile with the JSON reporter; or run the `json` command:

```
$> bundle exec inspec exec nginx_repro-0.1.0.tar.gz --reporter=json
bundler: failed to load command: inspec (/Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `encode'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `to_json'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `render'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters.rb:39:in `render'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:129:in `block in render_output'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `each'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `render_output'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:153:in `run_tests'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:122:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/cli.rb:269:in `exec'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `load'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `<top (required)>'

$> bundle exec inspec json nginx_repro-0.1.0.tar.gz
bundler: failed to load command: inspec (/Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `encode'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:394:in `dump'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/cli.rb:70:in `json'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `load'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Workaround**
Declaring `# encoding: UTF-8` at the top of `controls/example.rb` avoids the error.

### PR DESCRIPTION
**Pull request by zenspider**
Fixes #4135.

Signed-off-by: Ryan Davis <zenspider@chef.io>

### CODE REVIEW

**Review by james-stocks — APPROVED** [review]
Hi @zenspider -

Thanks very much for this!
I checked out this branch and re-tried the bug reproduction steps - this change looks good!
I also ran it in the CI task we use where the bug was found - looks good too :)

File: lib/inspec/file_provider.rb [hunk 1]
```diff
@@ -146,50 +146,56 @@ def read_from_zip(file)
...
+          # rubocop:disable Layout/MultilineOperationIndentation
+          # rubocop:disable Style/ParenthesesAroundCondition
+          next unless (entry.file? &&              # duh
+                       !name.empty? &&             # for empty filenames?
+                       name !~ %r{\.\.(?:/|\z)} && # .. (to avoid attacks?)
+                       !name.include?("PaxHeader/"))
+
+          path = Pathname.new(name).relative_path_from(here).to_s
+
+          @contents[path] = begin # not ||= in a tarball, last one wins
```
Comment (james-stocks) [inline lib/inspec/file_provider.rb:173]: Maybe this begin/end block could be moved out to a separate method like `attempt_utf8_encoding(entry.read)`

Just to avoid a hanging begin/end. But how it is currently seems good to merge too.

**Review by clintoncwolfe — APPROVED** [review]
Thanks for having such a clean commit stream - it made it much easier to follow. Thanks!
