### PR TITLE
Fix `only_if` behavior when used outside controls

### LINKED ISSUE #1914: Profile controls are not all being run with multiple rb files using only_if in some of them
### Description
Basically we have a profile with a list of controls. 

http.rb
php.rb
splunk.rb
sshd.rb
redhat_controls.rb

http.rb, php.rb, plunk.rb and sshd.rb all have only_if statements, which work great.   The redhat_controls does not have an only_if statement and is being skipped.   I renamed to controls_redhat.rb, now it seems all the controls are running.

### InSpec and Platform Version

1.26.0

client - 12.18.31

### Replication Case

create profile with multiple rb control files and include only_if statement, see if they are are checked running inspec

### Possible Solutions

Using only_if causing other controls to be skipped even though they do not have an only_if skip.   Does the order matter for the profiles

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This renames `@skip_profile` to `@skip_file` and modifies the scope of `only_if` (used outside of a control) to only apply to the control file that contains it instead of the entire profile.

This does this by exposing `@skip_file` from the control context so that it can be set back to `false` between loading control files in the profile context.

This fixes #1914

### CODE REVIEW

File: test/unit/profiles/profile_context_test.rb [hunk 1]
```diff
@@ -173,6 +174,15 @@ def load(call)
         get_checks.length.must_equal 1
         get_checks[0][1][0].resource_skipped.must_equal 'Skipped control due to only_if condition.'
       end
+
+      it 'doesnt extend into other control files' do
+        profile.load_control_file(if_false + control)
+        profile.load_control_file(control_2)
+        check_1 = get_checks
+        check_2 = Inspec::Rule.prepare_checks(profile.rules.values[1])
```
Comment (adamleff) [inline test/unit/profiles/profile_context_test.rb]: Can we add an optional parameter to get_checks to have it pull values other than the first? That way we're not defining this logic in multiple places.

**Review by adamleff — CHANGES_REQUESTED** [review]
This looks fine to me. I'd like to see us keep the call to `Inspec::Rule.prepare_checks` consolidated so we're not calling a combination of `get_checks` and a hand-crafted call to `Inspec::Rule.prepare_checks`.

File: test/unit/profiles/profile_context_test.rb (hunk 1 above)
Comment (jerryaldrichiii) [reply test/unit/profiles/profile_context_test.rb]: I agree! Fixed :smile:

**Comment by jerryaldrichiii** [comment]
I agree @adamleff. I modified `get_checks` to take a rule index.

**Comment by adamleff** [comment]
@jerryaldrichiii This change does not work for me locally. I have a profile with five controls files. Three of them have, at the file level:

```ruby
only_if { 1 == 2 }
```

One of them has:
```ruby
only_if { 1 == 1 }
```

And one has no `only_if`

When I exec this profile with your branch, all controls execute. When I exec against master, I get the initially-broken behavior.

My expectation is that I would've had two control files run, three skipped.

**Comment by adamleff** [comment]
Broken behavior on master:

```
  ✔  http: http
     ✔  http should cmp == "http"
  ↺  php: php
     ↺  Skipped control due to only_if condition.
  ↺  redhat: redhat
     ↺  Skipped control due to only_if condition.
  ↺  splunk: splunk
     ↺  Skipped control due to only_if condition.
  ↺  sshd: sshd
     ↺  Skipped control due to only_if condition.
```

... but redhat and splunk **should have* been run.

With this branch:

```
  ✔  http: http
     ✔  http should cmp == "http"
  ✔  php: php
     ✔  php should cmp == "php"
  ✔  redhat: redhat
     ✔  redhat should cmp == "redhat"
  ✔  splunk: splunk
     ✔  splunk should cmp == "splunk"
  ✔  sshd: sshd
     ✔  sshd should cmp == "sshd"
```

... but http, php, and sshd should've been skipped.

**Comment by jerryaldrichiii** [comment]
Looking at your examples I see that your `only_if` statements are at the bottom of the files vs the top.

I did not test with them at the bottom. I will add functional tests to avoid this in the future. I will also modify this to have the `only_if` apply to the whole file regardless of position.

File: lib/inspec/profile_context.rb [hunk 2]
```diff
@@ -127,6 +127,7 @@ def load_libraries(libs)
     end
 
     def load_control_file(*args)
+      control_eval_context.skip_file = false
```
Comment (adamleff) [inline lib/inspec/profile_context.rb]: I'm curious what this is needed for... isn't this false by default? It also feels weird to me for this to be disclosed as a public API on the control eval context, but perhaps I'm missing an idiosyncrasy.

**Review by adamleff — COMMENTED** [review]
@jerryaldrichiii this looks good - just a question before I approve.

File: lib/inspec/profile_context.rb (hunk 2 above)
Comment (jerryaldrichiii) [reply lib/inspec/profile_context.rb]: Ah, that was a tricky one! From what I could tell (and I could be wrong because this was quite a rabbit hole) is that we only create a `control_eval_context` once and it is set to `false` at that time. Then later on when an `only_if` evaluated to `false` we toggled that value to `true`.

The issue was caused because we never toggled that back to `false`. So I needed a way to set that to `false` between each evaluation/load of a control file. That was the only place I could find that fit the bill.

It also feels weird to me, but I'm not sure how to get around it. Suggestions are welcome!

Comment (adamleff) [reply lib/inspec/profile_context.rb]: Your explanation is spot-on. The fact that you had to explain it is the problem. :) A one-line code comment above this line explaining why this is necessary will fit the bill.

```
# Set skip_file to false before we read in a new file, just in case the prior file was skipped
```

Comment (jerryaldrichiii) [reply lib/inspec/profile_context.rb]: Great! I agree about the comment. It has been added.

**Comment by jerryaldrichiii** [comment]
Looks like I'm failing Rubocop due to:
```
lib/inspec/plugins/resource.rb:40:5: C: Method has too many lines. [49/40]
    def __register(name, obj) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

It's due to us defining a class in a method and the several methods I've added. @adamleff should we ignore this violation? If not, most of these methods can be defined on one line...but I don't like the way that looks. I'm open to other suggestions as well.

Also, thank you so much for all the effort you've put into these reviews. They helped the project and me greatly.

**Review by adamleff — APPROVED** [review]
Nicely done, @jerryaldrichiii!

**Review by chris-rock — APPROVED** [review]
Thank you @jerryaldrichiii That was a difficult one 🥇
