### PR TITLE
fix cli inherited profiles

### LINKED ISSUE #898: package() 'version' {should match(pattern)} does not return failed control, but shows as failed test
### Description

Looks like

```
  describe package('default-jdk') do
    it { should be_installed }
    its('version') { should match(java_version)  }
  end
```

is not maked as failed control section. I wonder if it is an intended behaviour or maybe I wrote tests incorrectly?
### InSpec and Platform Version

```
InSpec version: 0.29.0
Train version: 0.16.0
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
```
### Replication Case

Example test file (notice os[:name]):

```
title 'Default JDK'
java_version = '1:1.7' if os[:family] == 'debian'
java_version = '2:1.7' if os[:family] == 'ubuntu'

control 'default-jdk-001' do
  impact 1.0
  title 'default-jdk package should be installed'
  desc 'default-jdk package should be installed'
  describe package('default-jdk') do
    it { should be_installed }
    its('version') { should match(java_version)  }
  end
end
```

results in:

```
  ✔  default-jdk-001: System Package default-jdk should be installed
  ✔  jmeter-slave-001: File /mnt should be directory
  ✔  jmeter-slave-002: File /home/jmeter/ should be directory
  ✔  jmeter-user-001-xscreensaver-jmeter: File /home/jmeter/.xscreensaver content should match /(?!#)mode:\s.*off/
  ✔  jmeter-user-002: File /home/jmeter/ should be directory
  ✔  tools-001: System Package screen should be installed
  ✔  tools-002: System Package bzip2 should be installed
  ✔  package-bzip2: System Package bzip2 should be installed
  ✔  package-screen: System Package screen should be installed
  ✔  package-mc: System Package mc should be installed
  ✔  package-htop: System Package htop should be installed


Profile: InSpec Profile for Jmeter Master (xstream-jmeter-slave)
Version: 1.0.0
Target:  ssh://ubuntu@redacted:22

     No tests executed.

Summary: 20 successful, 1 failures, 0 skipped
```
### Possible Solutions

Proper test (with fixed code to os[:name] and package version test moved to separate control):

```
# encoding: utf-8

title 'Default JDK'
java_version = '1:1.7' if os[:name] == 'debian'
java_version = '2:1.7' if os[:name] == 'ubuntu'

control 'default-jdk-001' do
  impact 1.0
  title 'default-jdk package should be installed'
  desc 'default-jdk package should be installed'
  describe package('default-jdk') do
    it { should be_installed }
  end
end

control 'default-jdk-002' do
  impact 1.0
  title 'default-jdk package version'
  desc 'default-jdk package version'
  describe package('default-jdk') do
    its('version') { should match(java_version)  }
  end
end

```

results in proper output:

```
  ✔  default-jdk-001: System Package default-jdk should be installed
  ✖  default-jdk-002: System Package default-jdk version should match "1:1.7" (expected "2:1.7-51" to match "1:1.7")
  ✔  jmeter-slave-001: File /mnt should be directory
  ✔  jmeter-slave-002: File /home/jmeter/ should be directory
  ✔  jmeter-user-001-xscreensaver-jmeter: File /home/jmeter/.xscreensaver content should match /(?!#)mode:\s.*off/
  ✔  jmeter-user-002: File /home/jmeter/ should be directory
  ✔  tools-001: System Package screen should be installed
  ✔  tools-002: System Package bzip2 should be installed
  ✔  package-bzip2: System Package bzip2 should be installed
  ✔  package-screen: System Package screen should be installed
  ✔  package-mc: System Package mc should be installed
  ✔  package-htop: System Package htop should be installed


Profile: InSpec Profile for Jmeter Master (xstream-jmeter-slave)
Version: 1.0.0
Target:  ssh://ubuntu@redacted:22

     No tests executed.

Summary: 20 successful, 1 failures, 0 skipped
```
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

### PR DESCRIPTION
**Pull request by vjeffrey**
this is branched off the vj/fix-cli-report branch, so it needs to be rebased once that one merges. there's only one commit for this change, the fix inherited profile cli report commit
this fixes https://github.com/chef/inspec/issues/898

run inherited profile with my fix commented out: 
inherited - with my fix commented out

run inherited profile with my fix: 
inherited - with the fix

run inherited profile directly: 
run inherited profile directly

### CODE REVIEW

**Comment by chris-rock** [comment]
@vj this looks great. Can you fix the functional tests

**Comment by vjeffrey** [comment]
running two profiles from command line: 
screen shot 2016-09-02 at 1 02 28 pm

**Comment by vjeffrey** [comment]
@chris-rock all fixed :)

File: lib/inspec/rspec_json_formatter.rb [hunk 1]
```diff
@@ -164,10 +164,32 @@ def profile_info(profile)
     [info[:name], info]
   end
 
+  #
+  # TODO(ssd+vj): We should probably solve this by either ensuring the example has
```
Comment (chris-rock) [inline lib/inspec/rspec_json_formatter.rb:168]: +1 I like that idea
