### PR TITLE
Fix for --controls option is not working as expected.

### LINKED ISSUE #5215: InSpec CLI exec "--controls=foo" option is not working as expected
Using the [exec subcommand with option ](https://docs.chef.io/inspec/cli/#options-3)`--controls=foo` should only run the `foo` control, but it seems like it's still running all controls within the profile in background and only filtering the results output.
# Describe the problem
Have an InSpec profile with 3 controls: foo, bar, baz.

- Execute the InSpec profile without `--controls` option will run all three controls and will take e.g. 03:00 min.
- Execute the same InSpec profile with `--controls=foo` option should only run the one control, but it still takes 03:00 min. (Output is fine and only showing results for foo)
- Remove the other two controls (bar and baz) from the InSpec profile folder and then execute the profile will run only the one existing control and it will only take e.g. 00:25 min.

So it seems like that all controls in the profile folder affect the execution time, although only those selected with the option should be executed.

According to the option description only the selected controls should be run:
> `--controls=one two three` A list of control names to run, or a list of /regexes/ to match against control names. Ignore all other tests.

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

As mentioned in issue #5215 the control block also gets evaluated and due to which the `--controls ` option is not working as expected.
The reason behind that the filtering of control here https://github.com/inspec/inspec/blob/master/lib/inspec/profile.rb#L228 is happening after evaluating the controls which are happening here https://github.com/inspec/inspec/blob/master/lib/inspec/profile.rb#L220

which calls this https://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/profile_context.rb#L154 and then this https://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/profile_context.rb#L162

which then calls this control definition https://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/control_eval_context.rb#L54
and describe definition  (descrhttps://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/control_eval_context.rb#L66

both these methods instantiate Inspec::rule https://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/rule.rb#L46
which basically causing the skipped control is getting evaluated (note not the describe block)

I have added a method in the control_eval_context.rb to filter the controls before evaluating it. I need to add the filter in describe method also because when we are having only describe block without control block the methods creates auto-generated control as described here https://github.com/inspec/inspec/blob/2f41c16ad444eaf69f7ec77f4ff681f35aad9210/lib/inspec/control_eval_context.rb#L63
so I am making sure those describe blocks are also get filtered when specifying --controls option.

## Related Issue

Fixes #5215
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: test/functional/inspec_exec_test.rb [hunk 1]
```diff
@@ -178,6 +178,25 @@ def stderr
     assert_exit_code 100, out
   end
 
+  it "executes only specified controls when selecting the controls by literal names" do
+    inspec("exec " + File.join(profile_path, "filter_table") + " --no-create-lockfile --controls foo")
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_test.rb]: Why did you choose the filter_table fixture? I don't think this problem has anything to do with FilterTable. I would suggest either finding a different profile, or creating a new one just for this purpose.

File: test/functional/inspec_exec_test.rb [hunk 2]
```diff
@@ -178,6 +178,25 @@ def stderr
...
+    _(stdout).must_equal "
+Profile: InSpec Profile (filter_table)
+Version: 0.1.0
+Target:  local://
+
+  ✔  foo: a thing
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_test.rb]: This is likely too brittle of a test - the check marks vary under Windows, for example. I suggest you write tests that look specifically for what you are looking for. For example, 

```
_(out.stdout).wont_include "bar"
_(out.stdout).wont_include "baz"
```

File: test/functional/inspec_exec_test.rb (hunk 1 above)
Comment (Vasu1105) [reply test/functional/inspec_exec_test.rb]: Yes after checking the impact decided to remove this from here. I thought since we are using --controls options in test with this profile that will be good place to include. But yes definitely this is not the right place to have this. Making the required changes.

File: test/functional/inspec_exec_test.rb [hunk 3]
```diff
@@ -178,6 +178,27 @@ def stderr
...
+    inspec("exec " + File.join(profile_path, "controls-option-test") + " --no-create-lockfile --controls foo")
+    _(out.stdout).must_include "foo"
+    _(out.stdout).wont_include "bar"
+    _(out.stdout).wont_include "baz"
+    _(stderr).must_equal ""
+
+    assert_exit_code 0, out
+  end
+
+  it "executes only specified controls when selecting the controls by literal names" do
```
Comment (clintoncwolfe) [inline test/functional/inspec_exec_test.rb]: This selects by regex, not by literal name

File: test/fixtures/profiles/controls-option-test/controls/example.rb [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+
+  describe file('/') do                             # The actual test
+    it { should be_directory }
+  end
+end
+
+# you can also use plain tests
+describe file('/') do
+  it { should be_directory }
+end
```
Comment (clintoncwolfe) [inline test/fixtures/profiles/controls-option-test/controls/example.rb]: This file has a lot of extra material in it that is not being tested. Either it should be removed or it should be tested - fixture files should be minimal. Thanks!

**Review by clintoncwolfe — APPROVED** [review]
Just a couple of minor notes about the test fixture file, nit-picking really. This works really well. I think users will be very happy with this improvement!

File: test/functional/inspec_exec_test.rb (hunk 3 above)
Comment (Vasu1105) [reply test/functional/inspec_exec_test.rb]: Updated.

File: test/fixtures/profiles/controls-option-test/controls/example.rb (hunk 4 above)
Comment (Vasu1105) [reply test/fixtures/profiles/controls-option-test/controls/example.rb]: Thanks @clintoncwolfe .Did the required changes.

**Comment by klose4711** [comment]
Thanks for fixing this! 🙂
