### PR TITLE
Generate test labels for multi-test controls

### LINKED ISSUE #812: Inspec exec output when multiple matchers are used
With `inspec 0.26.0`, when multiple matchers are used, the output is missing the label of the test. For example, for the above test:

``` ruby
describe file('/etc') do
  it { should exist }
end

describe service('apache2') do
  it { should be_enabled }
  it { should be_running }
end
```

I get:

```
$ ~/git/inspec/bin/inspec exec s.rb --sudo --password '***' -t ssh://vagrant@***

  ✔  File /etc should exist
  ✔

Summary: 3 successful, 0 failures, 0 skipped
```

And for this test:

``` ruby
describe file('/etc') do
  it { should exist }
  its('mode') { should cmp '0755' }
end

describe service('apache2') do
  it { should be_running }
end
```

I get:

```
$ ~/git/inspec/bin/inspec exec s.rb --sudo --password '***' -t ssh://vagrant@***

  ✔
  ✔  Service apache2 should be running

Summary: 3 successful, 0 failures, 0 skipped

$ ~/git/inspec/bin/inspec version
0.26.0
```

### LINKED ISSUE #872: 1.10.2 missing a space in failed test output
With kitchen 1.10.2 as installed by ChefDK, I'm getting weird display errors for failing tests. This is when running tests on a guest Ubuntu 16 hosted in VirtualBox on OS X 10.11.6.

Here's a sample, but it does this on all failing tests, not just package tests

```
✖  System Package lockrun should be installedexpected that `System Package lockrun` is installed
```

### PR DESCRIPTION
**Pull request by ksubrama**
Fix #812
Fix #872

### CODE REVIEW

**Comment by ksubrama** [comment]
@chris-rock @stevendanna @arlimus

File: lib/inspec/rspec_json_formatter.rb [hunk 1]
```diff
@@ -237,23 +260,42 @@ def current_control_infos
...
+    if res.length == 1
+      # Single test - be nice and just print the exception message if the test
+      # failed. No need to say "1 failed".
+      fails.clear
+      skips.clear
+      c = res[0]
+      # If it's an anonymous control, just go with the only description
+      # available for the underlying test.
+      summary = c[:code_desc].to_s unless summary
+      summary + c[:message].to_s
```
Comment (stevendanna) [inline lib/inspec/rspec_json_formatter.rb]: Should we add a space in front of the message here?

File: lib/inspec/rspec_json_formatter.rb [hunk 2]
```diff
@@ -237,23 +260,42 @@ def current_control_infos
...
+    elsif res.length == 0
+      # Empty control block - if it's anonymous, there's nothing we can do.
+      # Is this case even possible?
+      summary = "Empty anonymous control" unless summary
```
Comment (stevendanna) [inline lib/inspec/rspec_json_formatter.rb]: I think you want something like: `summary || "Empty anonymous control"` otherwise this will return `nil` in the case that summary is already defined.

File: lib/inspec/rspec_json_formatter.rb [hunk 3]
```diff
@@ -237,23 +260,42 @@ def current_control_infos
...
+    else
```
Comment (stevendanna) [inline lib/inspec/rspec_json_formatter.rb:275]: I would consider pulling the code inside this else out into a function with a signature like `multi_test_summary(summary, results, fails, skips)`

**Comment by ksubrama** [comment]
@ssd I refactored it in a slightly different way but I think I hit all the issues you pointed out.

**Comment by stevendanna** [comment]
@ksubrama Nice refactor!

**Comment by stevendanna** [comment]
Also fixes: #872

**Comment by stevendanna** [comment]
👍 from me

**Comment by chris-rock** [comment]
Great work @ksubrama

**Comment by chris-rock** [comment]
screen shot 2016-08-05 at 1 52 33 pm
