### PR TITLE
Fix range based filtering in filter tables

### LINKED ISSUE #5116: FilterTable where filtering with ranges or inequalities
https://github.com/inspec/inspec/blob/master/docs/dev/filtertable-usage.md suggests that ranges in FilterTables where methods is possible. This doesn't appear to work as documented.

## Describe the problem
```ruby
  describe things.where(thing_id: (1..2)) do
    its('count') { should cmp 2 }
  end
```
actually returns
```
things.where(thing_id: (1..2))
=> Things with thing_id == 1..2
things.where(thing_id: (1..2)).entries
=> []
```
and does not return the expected two Things with ID 1 and 2. It returns no entries instead.

## Possible Solution
Either remove the example from FilterTable usage docs or fix/implement the behaviour.

Aha! Link: https://chef.aha.io/features/SH-2387

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

## Description

Fixed range based filtering in filter tables for issue explained below.

**Problem:** 

Issue with range based filtering : 
```
things.where(thing_id: (1..2)).entries
```
where data is 
```
[
   { thing_id: 1, color: :red },
   { thing_id: 2, color: :blue, tackiness: 'very' },
   { thing_id: 3, color: :red },
]
```
Returned [] entries while it should return first 2 entries.

## Related Issue

Fixes #5116 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by Vasu1105 — APPROVED** [review]
LGTM. Thanks @Nik08. Good work !!

**Comment by Nik08** [comment]
Thanks @Vasu1105 :)

File: lib/inspec/utils/filter.rb [hunk 1]
```diff
@@ -256,7 +256,7 @@ def matches_regex(x, y)
     end
 
     def matches(x, y)
-      x === y # rubocop:disable Style/CaseEquality
+      y === x # rubocop:disable Style/CaseEquality
```
Comment (clintoncwolfe) [inline lib/inspec/utils/filter.rb:259]: Would you mind explaining the fix?

Comment (Nik08) [reply lib/inspec/utils/filter.rb:259]: Yes sure. So this method is called when the filter table needs to match anything other than an Integer, float & regex. So this is the `else` condition. And since this one was called in case of **ranges**. It was breaking because I found it was checking initially for example `1 === 1..2` while my change checks for `1..2 === 1` and this returns true because this is how it should be used for this case. I referred [this](https://stackoverflow.com/questions/4467538/what-does-the-operator-do-in-ruby).
