### PR TITLE
Fix issue Dir.home would break when HOME env absent

### LINKED ISSUE #4803: couldn't find login name -- expanding `~' (ArgumentError)
Inspec version - 4.18.51

I am trying to inspec target VM by ssh. 

Command used:
inspec exec /path/script.rb --host <host> --port <port> --backend ssh --user <username> --password <password> --reporter json

I am getting expected output when I execute this command with argument values from terminal(ubuntu). I am using python subprocess to call this and got error.

 /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/globals.rb:3:in `home': couldn't find login name -- expanding `~' (ArgumentError)

How come the command is working in terminal and why it is not working in script?

Thanks

### PR DESCRIPTION
**Pull request by kvivek1115**
## Description

Fix the issue `Dir.home` would break when home directory lookup fail. when HOME even var is not set.
as `$HOME` is not set in systemd service `File.expand_path('~')` will not work here

## Related Issue

Fixes https://github.com/inspec/inspec/issues/4803, https://github.com/chef/chef/issues/10565

Steps to reproduce
- `unset HOME`
- `ruby -e 'print Dir.home'`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

File: lib/inspec/globals.rb [hunk 1]
```diff
@@ -1,11 +1,20 @@
...
   extend Inspec::InstallContextHelpers
-
+  
   def self.config_dir
-    ENV["INSPEC_CONFIG_DIR"] ? ENV["INSPEC_CONFIG_DIR"] : File.join(Dir.home, ".inspec")
+    begin
+  	  home = Dir.home
+  	rescue ArgumentError, NoMethodError
+  	  # $HOME is not set in systemd service File.expand_path('~') will not work here
+  	  home = Etc.getpwuid(Process.uid).dir
```
Comment (clintoncwolfe) [inline lib/inspec/globals.rb]: It looks like you can simplify this to `Etc.getpwiud.dir`

File: lib/inspec/globals.rb [hunk 2]
```diff
@@ -1,11 +1,20 @@
...
 
   extend Inspec::InstallContextHelpers
-
+  
   def self.config_dir
-    ENV["INSPEC_CONFIG_DIR"] ? ENV["INSPEC_CONFIG_DIR"] : File.join(Dir.home, ".inspec")
+    begin
+  	  home = Dir.home
+  	rescue ArgumentError, NoMethodError
+  	  # $HOME is not set in systemd service File.expand_path('~') will not work here
```
Comment (clintoncwolfe) [inline lib/inspec/globals.rb]: Might want to make this comment more general, something like:
"If ENV['HOME'] is not set, Dir.home will fail due to expanding the ~. Fallback to Etc."

File: lib/inspec/globals.rb [hunk 3]
```diff
@@ -1,11 +1,20 @@
 require_relative "utils/install_context"
 
+require 'etc' unless defined?(Etc)
```
Comment (clintoncwolfe) [inline lib/inspec/globals.rb]: Could we move this into the rescue block, so we only require it if needed?

**Review by clintoncwolfe — COMMENTED** [review]
Hi! I think the fallback to Etc is a good approach. A few small comments to address but nothing major.

In addition:
 * Please run the linter on your code - run `bundle exec chefstyle -a` to fix the code style issues.
 * Please rebase your code against master to pick up fixes for the Ruby 2.5 tests.

Thanks!

File: lib/inspec/globals.rb (hunk 2 above)
Comment (kvivek1115) [reply lib/inspec/globals.rb]: Make sense to me thanks!

**Review by clintoncwolfe — APPROVED** [review]
